package com.kirinonakar.calcmax.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

/** The saved language is independent of Android's system locale. Math commands remain English. */
val LocalLanguage = staticCompositionLocalOf { "en" }

private val korean = mapOf(
    "Yates continuity correction" to "Yates 연속성 보정",
    "Applies only to 2×2 tables. Turn off for Pearson χ²." to "2×2 표에만 적용됩니다. 끄면 보정 없는 Pearson χ²를 계산합니다.",
    "Probability" to "확률 계산", "Calculation" to "계산 종류", "Distribution" to "확률 분포",
    "Calculate probability" to "확률 계산", "Reset inputs" to "초기화", "Independent events" to "독립 사건",
    "Calculate parameter" to "모수 계산",
    "Probability examples" to "확률 예제", "Probability operation" to "확률 계산 방식",
    "Favorable outcomes" to "원하는 경우 수", "Total outcomes" to "전체 경우 수",
    "Probability distribution preview" to "확률 분포 미리보기",
    "Range · 0.1%–99.9% quantiles" to "범위 · 0.1%~99.9% 분위수",
    "Preview samples integer masses; some counts are omitted." to "정수별 확률질량을 표본으로 표시하며 일부 횟수는 생략됩니다.",
    "Normal solver requires 0 < q < 1" to "정규 분포 모수 역산에서는 0 < q < 1이어야 합니다",
    "No positive σ satisfies these inputs" to "입력 조건을 만족하는 양수 σ가 없습니다",
    "σ is not uniquely determined when q = 0.5 and x = μ" to "q = 0.5이고 x = μ이면 σ는 하나로 정해지지 않습니다",
    "μ = x − σz, where z is the standard normal quantile." to "μ = x − σz이며 z는 표준정규 분포의 분위수입니다.",
    "σ = (x − μ) / z, where z is the standard normal quantile." to "σ = (x − μ) / z이며 z는 표준정규 분포의 분위수입니다.",
    "undefined" to "정의되지 않음",
    "Mass / density preview" to "확률질량 · 밀도 미리보기",
    "Preview · shaded region is the selected event" to "미리보기 · 색칠한 부분이 선택한 사건",
    "Independent events: P(A ∩ B) = P(A) × P(B)." to "독립 사건: P(A ∩ B) = P(A) × P(B).",
    "Trials are independent with the same success probability." to "성공 확률이 같은 독립 시행입니다.",
    "Geometric X counts trials through the first success (starting at 1)." to "첫 성공까지의 시행 수입니다 (1부터 셉니다).",
    "Negative binomial X counts failures before the r-th success (starting at 0). Total trials = X + r." to "X는 r번째 성공 전까지의 실패 횟수입니다 (0부터 셉니다). 총 시행 수 = X + r.",
    "Negative binomial X counts failures before the r-th success (starting at 0). Total trials = X + r. Smallest supported integer with P(X ≤ x) ≥ q." to "X는 r번째 성공 전까지의 실패 횟수입니다 (0부터 셉니다). 총 시행 수 = X + r. P(X ≤ x) ≥ q를 만족하는 가장 작은 정수입니다.",
    "X counts selected specified items; drawing is without replacement." to "X는 지정 항목 중 뽑힌 개수이며, 중복 없이 뽑습니다.",
    "Smallest supported integer with P(X ≤ x) ≥ q." to "P(X ≤ x) ≥ q를 만족하는 가장 작은 정수입니다.",
    "Inverse cumulative probability." to "누적 확률에 해당하는 값입니다.",
    "Density is not a probability and may exceed 1. For continuous X, P(X = x) = 0." to "밀도는 확률이 아니므로 1보다 클 수 있습니다. 연속 분포에서 P(X = x) = 0입니다.",
    "Enter a number, fraction, or percentage" to "숫자 · 분수 · 백분율을 입력하세요",
    "Enter an integer within the allowed range" to "허용 범위의 정수를 입력하세요",
    "Probabilities must be between 0 and 1" to "확률은 0부터 1 사이여야 합니다",
    "This parameter must be greater than zero" to "0보다 큰 값을 입력하세요",
    "Division by zero in input" to "입력값을 0으로 나눌 수 없습니다",
    "Enter a finite number" to "유한한 숫자를 입력하세요", "Numeric input is too long" to "입력값이 너무 깁니다",
    "Favorable outcomes must not exceed a positive total" to "전체 경우 수는 양수이고, 원하는 경우 수 이상이어야 합니다",
    "Dice count and sides must be positive" to "주사위 개수와 면 수는 양수여야 합니다",
    "Draws and specified items must not exceed total" to "뽑을 수와 지정한 수는 전체 수 이하여야 합니다",
    "Selection count must not exceed item count" to "선택 수는 항목 수 이하여야 합니다",
    "Success count must not exceed trial count" to "성공 횟수는 시행 횟수 이하여야 합니다",
    "Cannot select from zero items" to "항목이 없으면 선택할 수 없습니다",
    "Intersection is inconsistent with P(A) and P(B)" to "교집합 확률이 P(A), P(B)와 맞지 않습니다",
    "Conditioning event has zero probability" to "조건 사건의 확률이 0입니다",
    "Given probability" to "주어진 확률",
    "Add given probability" to "주어진 확률 추가",
    "Remove given probability" to "주어진 확률 제거",
    "Choose at least one given probability" to "주어진 확률을 하나 이상 선택하세요",
    "Given probabilities are inconsistent" to "주어진 확률들이 서로 맞지 않습니다",
    "Given probabilities do not determine a unique answer" to "주어진 확률만으로는 답을 하나로 정할 수 없습니다. 필요한 확률을 추가하세요",
    "Success probability must be greater than zero" to "성공 확률은 0보다 커야 합니다",
    "Required successes must be greater than zero" to "목표 성공 횟수는 0보다 커야 합니다",
    "Average count must be between 0 and 100000" to "평균 발생 횟수는 0부터 100000 사이여야 합니다",
    "Draws and success items must not exceed population" to "추출 수와 성공 항목 수는 모집단 크기 이하여야 합니다",
    "Maximum must be greater than minimum" to "최댓값은 최솟값보다 커야 합니다",
    "Lower bound must not exceed upper bound" to "구간 하한은 상한 이하여야 합니다",
    "Quantile exceeds numerical range" to "분위수가 계산 가능한 범위를 넘었습니다",
    "Calculation failed" to "계산하지 못했습니다", "Numeric exponent is too large" to "입력 지수가 너무 큽니다",
    "Graph colors" to "그래프 색", "Graph color" to "그래프 색",
    "Hue (H)" to "색조 (H)", "Saturation (S)" to "채도 (S)", "Lightness (L)" to "명도 (L)",
    "Reset color" to "색 초기화", "Reset all colors" to "전체 색 초기화",
    "Graph limit reached. Remove a function before adding another." to "그래프 개수 한도에 도달했습니다. 기존 함수를 지운 뒤 추가하세요.",
    "Calculation mode" to "계산 모드", "Choose calculation mode, long press for Scientific/CAS mode" to "계산 모드 선택, 길게 누르면 Scientific/CAS 모드",
    "Stored memory" to "저장된 메모리", "Overwrite mode" to "덮어쓰기 모드", "Insert mode" to "삽입 모드",
    "Clear" to "지우기", "Close" to "닫기", "Done" to "완료", "Cancel" to "취소", "Apply" to "적용",
    "Undo" to "실행 취소", "Cut" to "잘라내기", "Copy" to "복사", "Copy =" to "답 복사", "Copy expr" to "수식 복사",
    "Paste" to "붙여넣기", "Keyboard" to "키보드", "Math input" to "수식 입력",
    "Show exact" to "정확값 보기", "Show decimal" to "소수 보기",
    "Expression input" to "수식 입력", "Undo last input" to "마지막 입력 취소",
    "Instrument setup" to "계산기 설정", "Language" to "언어", "Appearance" to "화면 모양",
    "System" to "시스템", "Light" to "밝게", "Dark" to "어둡게", "Angle unit" to "각도 단위",
    "Internal precision · numeric algorithms" to "내부 정밀도 · 수치 계산", "Display digits · decimal places shown" to "표시 자릿수 · 소수점 아래 자릿수",
    "Custom" to "사용자 지정", "Custom internal precision · 3–200" to "내부 정밀도 직접 입력 · 3–200",
    "Custom display digits · 2–200" to "표시 자릿수 직접 입력 · 2–200",
    "Apply internal precision" to "내부 정밀도 적용", "Apply display digits" to "표시 자릿수 적용",
    "Input font" to "입력 글자", "Output font" to "결과 글자", "Key vibration" to "키 진동",
    "Key sound" to "키 소리", "Save history locally" to "기록을 기기에 저장", "Bracket auto-close" to "괄호 자동 닫기",
    "Calculation history" to "계산 기록", "Search history" to "기록 검색", "All" to "전체", "Recent" to "최근", "Favorites" to "즐겨찾기",
    "Reuse" to "다시 사용", "Delete" to "삭제", "Clear all" to "모두 지우기",
    "Function catalog" to "함수 카탈로그", "Function catalog - help" to "함수 카탈로그 도움말",
    "Help" to "도움말", "Find function" to "함수 찾기", "Search" to "검색",
    "Open the function catalog help" to "함수 카탈로그 도움말 열기", "Loading the catalog reference..." to "카탈로그 설명을 불러오는 중...",
    "Example:" to "예:", "Save a function in Functions to see it here." to "Functions에서 함수를 저장하면 여기에 표시됩니다.",
    "Graph types" to "그래프 종류", "Plot" to "그리기", "Range" to "범위", "Analyze" to "분석", "Table" to "표",
    "Animate" to "애니메이션", "Stop" to "중지", "Parameters ▾" to "매개변수 ▾", "Parameters ▸" to "매개변수 ▸",
    "Fit Y" to "Y 범위 맞춤", "Root" to "근", "Y-intercept" to "y절편", "Intersection" to "교점", "Minimum" to "최솟값",
    "Maximum" to "최댓값", "Inflection" to "변곡점", "Derivative" to "도함수", "Tangent" to "접선",
    "Integral" to "적분", "Arc length" to "호의 길이", "Trace x" to "x 추적",
    "Equation" to "방정식", "Solution" to "해", "Solve" to "풀기", "Solving…" to "푸는 중…",
    "Variable" to "변수", "Variables" to "변수", "Initial guess" to "초깃값",
    "Custom functions" to "사용자 함수", "Import" to "가져오기", "Export" to "내보내기", "Save" to "저장",
    "New" to "새 파일", "Open" to "열기", "Save as" to "다른 이름으로 저장", "Run" to "실행",
    "Running…" to "실행 중…", "Output" to "출력", "Input" to "입력",
    "Data & statistics" to "데이터 및 통계",
    "Summary" to "요약", "Regression" to "회귀", "Tests" to "검정", "Intervals" to "신뢰구간",
    "Import CSV" to "CSV 가져오기", "Export CSV" to "CSV 내보내기",
    "First row is a header" to "첫 행이 헤더", "Header detected automatically" to "헤더를 자동으로 인식했습니다",
    "No header detected" to "헤더가 감지되지 않았습니다", "Import as" to "가져올 데이터 형식",
    "Choose a CSV column for each variable" to "각 변수에 사용할 CSV 열을 선택하세요", "Preview" to "미리보기",
    "Result" to "결과", "Calculate" to "계산", "Amount" to "금액",
    "One equation per line" to "한 줄에 방정식 하나",
    "Variables · comma separated" to "변수 · 쉼표로 구분", "Solve for" to "풀이 변수",
    "Differential equation" to "상미분방정식", "Partial differential equation" to "편미분방정식",
    "Dependent function" to "종속 함수", "Independent variable" to "독립 변수",
    "Initial conditions (optional)" to "초기 조건 (선택)", "Hint (optional)" to "풀이 힌트 (선택)",
    "Example: y(0)=1 or [y(0)=1,y(1)=2]" to "예: y(0)=1 또는 [y(0)=1,y(1)=2]",
    "Name" to "이름", "Parameters" to "매개변수", "Formula" to "공식", "Save function" to "함수 저장",
    "Edit" to "편집", "Insert" to "삽입", "Python code" to "Python 코드", "Enter" to "입력",
    "Open .py" to ".py 열기",
    "Indent" to "들여쓰기", "Outdent" to "내어쓰기",
    "Discard" to "버리기", "Unsaved changes" to "저장하지 않은 변경 사항",
    "Reset" to "초기화", "Reset ranges" to "범위 초기화", "Reset sliders" to "슬라이더 초기화", "Rotate" to "회전", "Tilt" to "기울기", "Zoom" to "확대", "Half height" to "높이 ½", "Full height" to "전체 높이",
    "Graph range" to "그래프 범위", "Automatic z range" to "z 범위 자동 설정",
    "One [x(t),y(t)] pair per line" to "한 줄에 [x(t),y(t)] 한 쌍",
    "r(t) · radians · one curve per line" to "r(t) · 라디안 · 한 줄에 곡선 하나",
    "u(n) · use u(n−1) for recurrences" to "u(n) · 점화식에는 u(n−1) 사용",
    "Implicit Graph" to "Implicit Graph(음함수 그래프)",
    "F(x,y)=0 · e.g. x^2+y^2=1" to "F(x,y)=0 · 예: x^2+y^2=1",
    "Invalid implicit y range" to "음함수 그래프의 y 범위를 확인해 주세요.",
    "Cartesian" to "카테시안",
    "Enter a function y=f(x) or an equation F(x,y)=0" to "함수 y=f(x) 또는 방정식 F(x,y)=0을 입력하세요.",
    "Graph an expression, y = f(x), or an equation F(x,y)=0" to "수식, 함수 y=f(x) 또는 방정식 F(x,y)=0을 입력하세요.",
    "Tap a point on the curve to choose a branch" to "곡선의 점을 눌러 분석할 가지를 선택하세요.",
    "Curve is undefined at this x coordinate" to "이 x 좌표에서 곡선이 정의되지 않습니다.",
    "Derivative graph requires branches expressible as y=f(x)" to "도함수 그래프에는 y=f(x)로 나타낼 수 있는 가지가 필요합니다.",
    "This curve cannot be analyzed as y=f(x) branches" to "이 곡선은 y=f(x) 가지로 분석할 수 없습니다.",
    "These curves cannot be analyzed as y=f(x) branches" to "이 곡선들은 y=f(x) 가지로 분석할 수 없습니다.",
    "The curve lies on the x axis; roots are not isolated" to "곡선이 x축 위에 있어 근을 개별 점으로 나타낼 수 없습니다.",
    "Select two different curves" to "서로 다른 두 곡선을 선택하세요.",
    "Enter one to six implicit equations" to "음함수 방정식을 1~6개 입력하세요.",
    "Enter an equation F(x,y)=0" to "F(x,y)=0 형태의 방정식을 입력하세요.",
    "Equation is true everywhere; enter a curve equation" to "모든 점에서 참인 식입니다. 곡선을 정의하는 방정식을 입력하세요.",
    "f(x) · one per line · [shade] y<f(x) or f, g" to "f(x) · 한 줄에 하나 · 음영: [shade] y<f(x) 또는 f, g",
    "One curve per line · [shade] / [s] -1<x<1 ,-1<y<x · between functions: [s] f, g" to "한 줄에 하나 · [shade] / [s] -1<x<1 ,-1<y<x · 두 함수 사이: [s] f, g",
    "Initial values at n=0 · comma separated" to "n=0의 초깃값 · 쉼표로 구분",
    "Initial time t₀" to "초기 시각 t₀", "Initial y values · comma separated" to "y 초깃값 · 쉼표로 구분",
    "Vector workspace" to "벡터 작업 공간", "Matrix workspace" to "행렬 작업 공간",
    "Insert into calculator" to "계산기에 넣기", "Clear grid" to "격자 지우기", "Operations" to "연산",
    "Operations with the second operand" to "두 번째 피연산자를 사용하는 연산",
    "Variable name or literal such as [[4,5,6]]" to "변수 이름 또는 [[4,5,6]] 같은 값",
    "Stored values · tap to use as the second operand" to "저장된 값 · 누르면 두 번째 피연산자로 사용",
    "Enter values once, then summarize, test, or plot the current dataset." to "데이터를 입력한 뒤 요약, 검정 또는 그래프로 분석합니다.",
    "Dataset name" to "데이터 이름", "Add row" to "행 추가", "One value per line" to "한 줄에 값 하나", "x,y,z data" to "x,y,z 데이터",
    "Direct input" to "직접 입력", "Table editor" to "표 편집",
    "Quick summaries" to "빠른 요약", "Visualize" to "시각화", "Summarize y" to "y 요약",
    "Correlation coefficient (r)" to "상관계수 (r)",
    "Clear regression" to "회귀선 지우기", "Graph fitted expression" to "적합식 그래프로 보기",
    "Independent variable" to "독립변수", "Initial values and bounds (optional)" to "시작값과 범위 (선택)",
    "Custom fitting did not converge to identifiable parameters. Try initial values or bounds, or simplify the model." to "매개변수를 결정할 수 있는 해로 피팅이 수렴하지 않았습니다. 시작값이나 범위를 지정하거나 모델을 단순하게 바꿔 주세요.",
    "Fit custom model" to "사용자 수식 피팅", "ADC example" to "ADC 예제", "IVIM example" to "IVIM 예제", "Exponential decay example" to "지수 감쇠 예제", "Model y =" to "모델 y =", "Fitted parameters" to "피팅 매개변수",
    "Query" to "질의", "Degrees of freedom" to "자유도",
    "Trials n" to "시행 횟수 n", "Success probability p" to "성공 확률 p",
    "Mean λ" to "평균 λ", "Mean μ" to "평균 μ", "Standard deviation σ" to "표준편차 σ",
    "a (lower bound)" to "a (하한)", "b (upper bound)" to "b (상한)",
    "Probability p (0–1)" to "확률 p (0–1)", "Compute" to "계산",
    "Analyze current data" to "현재 데이터 분석", "Hypothesized difference Δ₀" to "가정한 차이 Δ₀",
    "Hypothesized mean μ₀" to "가정한 평균 μ₀", "Confidence level (0–1 or %)" to "신뢰수준 (0–1 또는 %)",
    "Known σx" to "알려진 σx", "Known σ" to "알려진 σ", "Known σy" to "알려진 σy",
    "Alternative hypothesis" to "대립가설", "Alternative odds ratio (ordered categories)" to "대립 오즈비 (순서 있는 범주)",
    "Insert expression" to "수식 넣기", "Signed interpretation" to "부호 있는 값으로 해석",
    "Scientific constants" to "과학 상수",
    "Recall variable" to "변수 불러오기", "No stored variables" to "저장된 변수가 없습니다",
    "Delete all" to "모두 삭제", "Delete all variables" to "변수 모두 삭제", "Variables & functions" to "변수와 함수",
    "Stats data" to "통계 데이터", "Saved stats data · tap to recall" to "저장된 통계 데이터 · 누르면 불러오기",
    "Columns" to "열별 그룹", "x=group, y=value" to "x=그룹, y=값", "First group" to "첫 번째 그룹", "Second group" to "두 번째 그룹", "Group" to "그룹",
    "Stored values · tap to select" to "저장된 값 · 눌러서 선택", "Value / expression" to "값 / 수식",
    "User function" to "사용자 함수", "Parameters (comma separated)" to "매개변수 (쉼표로 구분)",
    "Store" to "저장", "Recall" to "불러오기", "Matrix size" to "행렬 크기",
    "Tip calculator" to "팁 계산", "Currency converter" to "통화 변환", "Online / cache" to "온라인 / 저장된 환율",
    "Manual" to "직접 입력", "Bill before tax" to "세전 금액", "Tip amount" to "팁 금액", "Number of people" to "인원수",
    "From (ISO code)" to "변환 전 (ISO 코드)", "To (ISO code)" to "변환 후 (ISO 코드)",
    "⇄ Swap currencies" to "⇄ 통화 맞바꾸기", "Drop decimals" to "소수점 버리기",
    "Update rates" to "환율 갱신", "Customize display buttons" to "표시 버튼 설정",
    "+ Add button" to "+ 버튼 추가", "Find button or function" to "버튼 또는 함수 찾기",
    "No matching buttons" to "일치하는 버튼이 없습니다", "Restore defaults" to "기본값 복원"
)

@Composable
fun tr(english: String): String = if (LocalLanguage.current == "ko") korean[english] ?: english else english

@Composable
fun isKorean(): Boolean = LocalLanguage.current == "ko"
