package com.kirinonakar.calcmax.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

/** The saved language is independent of Android's system locale. Math commands remain English. */
val LocalLanguage = staticCompositionLocalOf { "en" }

private val korean = mapOf(
    "Calculation mode" to "계산 모드", "Choose calculation mode, long press for Scientific/CAS mode" to "계산 모드 선택, 길게 누르면 Scientific/CAS 모드",
    "Stored memory" to "저장된 메모리", "Overwrite mode" to "덮어쓰기 모드", "Insert mode" to "삽입 모드",
    "Clear" to "지우기", "Close" to "닫기", "Done" to "완료", "Cancel" to "취소", "Apply" to "적용",
    "Undo" to "실행 취소", "Cut" to "잘라내기", "Copy" to "복사", "Copy =" to "답 복사", "Copy expr" to "수식 복사",
    "Paste" to "붙여넣기", "Keyboard" to "키보드", "Math input" to "수식 입력",
    "Show exact" to "정확값 보기", "Show decimal" to "소수 보기",
    "Expression input" to "수식 입력", "Undo last input" to "마지막 입력 취소",
    "Instrument setup" to "계산기 설정", "Language" to "언어", "Appearance" to "화면 모양",
    "System" to "시스템", "Light" to "밝게", "Dark" to "어둡게", "Angle unit" to "각도 단위",
    "Internal precision · numeric algorithms" to "내부 정밀도 · 수치 계산", "Display digits · result digits shown" to "표시 자릿수 · 결과에 보이는 자릿수",
    "Custom" to "사용자 지정", "Custom internal precision · 3–200" to "내부 정밀도 직접 입력 · 3–200",
    "Custom display digits · 2–200" to "표시 자릿수 직접 입력 · 2–200",
    "Apply internal precision" to "내부 정밀도 적용", "Apply display digits" to "표시 자릿수 적용",
    "Input font" to "입력 글자", "Output font" to "결과 글자", "Key vibration" to "키 진동",
    "Key sound" to "키 소리", "Save history locally" to "기록을 기기에 저장", "Bracket auto-close" to "괄호 자동 닫기",
    "Calculation history" to "계산 기록", "Search history" to "기록 검색", "All" to "전체", "Favorites" to "즐겨찾기",
    "Reuse" to "다시 사용", "Delete" to "삭제", "Clear all" to "모두 지우기",
    "Function catalog" to "함수 카탈로그", "Function catalog - help" to "함수 카탈로그 도움말",
    "Help" to "도움말", "Find function" to "함수 찾기", "Search" to "검색",
    "Open the function catalog help" to "함수 카탈로그 도움말 열기", "Loading the catalog reference..." to "카탈로그 설명을 불러오는 중...",
    "Example:" to "예:", "Save a function in Functions to see it here." to "Functions에서 함수를 저장하면 여기에 표시됩니다.",
    "Graph types" to "그래프 종류", "Plot" to "그리기", "Range" to "범위", "Analyze" to "분석", "Table" to "표",
    "Animate" to "애니메이션", "Stop" to "중지", "Parameters ▾" to "매개변수 ▾", "Parameters ▸" to "매개변수 ▸",
    "Fit Y" to "Y 범위 맞춤", "Root" to "근", "Intersection" to "교점", "Minimum" to "최솟값",
    "Maximum" to "최댓값", "Inflection" to "변곡점", "Derivative" to "도함수", "Tangent" to "접선",
    "Integral" to "적분", "Arc length" to "호의 길이", "Trace x" to "x 추적",
    "Equation" to "방정식", "Solution" to "해", "Solve" to "풀기", "Solving…" to "푸는 중…",
    "Variable" to "변수", "Variables" to "변수", "Initial guess" to "초깃값",
    "Custom functions" to "사용자 함수", "Import" to "가져오기", "Export" to "내보내기", "Save" to "저장",
    "New" to "새 파일", "Open" to "열기", "Save as" to "다른 이름으로 저장", "Run" to "실행",
    "Running…" to "실행 중…", "Output" to "출력", "Input" to "입력",
    "Data & statistics" to "데이터 및 통계",
    "Summary" to "요약", "Regression" to "회귀", "Tests" to "검정", "Intervals" to "신뢰구간",
    "Import CSV" to "CSV 가져오기", "Export CSV" to "CSV 내보내기",
    "Result" to "결과", "Calculate" to "계산", "Amount" to "금액",
    "One equation per line" to "한 줄에 방정식 하나",
    "Variables · comma separated" to "변수 · 쉼표로 구분", "Solve for" to "풀이 변수",
    "Name" to "이름", "Parameters" to "매개변수", "Formula" to "공식", "Save function" to "함수 저장",
    "Edit" to "편집", "Insert" to "삽입", "Python code" to "Python 코드", "Enter" to "입력",
    "Open .py" to ".py 열기",
    "Discard" to "버리기", "Unsaved changes" to "저장하지 않은 변경 사항",
    "Reset" to "초기화", "Reset sliders" to "슬라이더 초기화", "Rotate" to "회전", "Tilt" to "기울기", "Zoom" to "확대",
    "Graph range" to "그래프 범위", "Automatic z range" to "z 범위 자동 설정",
    "One [x(t),y(t)] pair per line" to "한 줄에 [x(t),y(t)] 한 쌍",
    "r(t) · radians · one curve per line" to "r(t) · 라디안 · 한 줄에 곡선 하나",
    "u(n) · use u(n−1) for recurrences" to "u(n) · 점화식에는 u(n−1) 사용",
    "f(x) · one per line · [shade] y<f(x) or f, g" to "f(x) · 한 줄에 하나 · 음영: [shade] y<f(x) 또는 f, g",
    "Initial values at n=0 · comma separated" to "n=0의 초깃값 · 쉼표로 구분",
    "Initial time t₀" to "초기 시각 t₀", "Initial y values · comma separated" to "y 초깃값 · 쉼표로 구분",
    "Vector workspace" to "벡터 작업 공간", "Matrix workspace" to "행렬 작업 공간",
    "Insert into calculator" to "계산기에 넣기", "Clear grid" to "격자 지우기", "Operations" to "연산",
    "Operations with the second operand" to "두 번째 피연산자를 사용하는 연산",
    "Variable name or literal such as [[4,5,6]]" to "변수 이름 또는 [[4,5,6]] 같은 값",
    "Stored values · tap to use as the second operand" to "저장된 값 · 누르면 두 번째 피연산자로 사용",
    "Enter values once, then summarize, test, or plot the current dataset." to "데이터를 입력한 뒤 요약, 검정 또는 그래프로 분석합니다.",
    "Dataset name" to "데이터 이름", "Add row" to "행 추가", "One value per line" to "한 줄에 값 하나",
    "Direct input" to "직접 입력", "Table editor" to "표 편집",
    "Quick summaries" to "빠른 요약", "Visualize" to "시각화", "Summarize y" to "y 요약",
    "Correlation coefficient (r)" to "상관계수 (r)",
    "Clear regression" to "회귀선 지우기", "Graph fitted expression" to "적합식 그래프로 보기",
    "Query" to "질의", "Degrees of freedom" to "자유도",
    "Trials n" to "시행 횟수 n", "Success probability p" to "성공 확률 p",
    "Mean λ" to "평균 λ", "Mean μ" to "평균 μ", "Standard deviation σ" to "표준편차 σ",
    "a (lower bound)" to "a (하한)", "b (upper bound)" to "b (상한)",
    "Probability p (0–1)" to "확률 p (0–1)", "Compute" to "계산",
    "Analyze current data" to "현재 데이터 분석", "Hypothesized difference Δ₀" to "가정한 차이 Δ₀",
    "Hypothesized mean μ₀" to "가정한 평균 μ₀", "Confidence level (0–1 or %)" to "신뢰수준 (0–1 또는 %)",
    "Known σx" to "알려진 σx", "Known σ" to "알려진 σ", "Known σy" to "알려진 σy",
    "Alternative hypothesis" to "대립가설", "Alternative odds ratio (ordered categories)" to "대립 오즈비 (순서 있는 범주)",
    "Insert expression" to "수식 넣기", "Signed interpretation" to "부호 있는 값으로 해석",
    "Scientific constants" to "과학 상수",
    "Recall variable" to "변수 불러오기", "No stored variables" to "저장된 변수가 없습니다",
    "Delete all" to "모두 삭제", "Variables & functions" to "변수와 함수",
    "Stored values · tap to select" to "저장된 값 · 눌러서 선택", "Value / expression" to "값 / 수식",
    "User function" to "사용자 함수", "Parameters (comma separated)" to "매개변수 (쉼표로 구분)",
    "Store" to "저장", "Recall" to "불러오기", "Matrix size" to "행렬 크기",
    "Tip calculator" to "팁 계산", "Currency converter" to "통화 변환", "Online / cache" to "온라인 / 저장된 환율",
    "Manual" to "직접 입력", "Bill before tax" to "세전 금액", "Tip amount" to "팁 금액", "Number of people" to "인원수",
    "From (ISO code)" to "변환 전 (ISO 코드)", "To (ISO code)" to "변환 후 (ISO 코드)",
    "⇄ Swap currencies" to "⇄ 통화 맞바꾸기", "Drop decimals" to "소수점 버리기",
    "Update rates" to "환율 갱신", "Customize display buttons" to "표시 버튼 설정",
    "+ Add button" to "+ 버튼 추가", "Find button or function" to "버튼 또는 함수 찾기",
    "No matching buttons" to "일치하는 버튼이 없습니다", "Restore defaults" to "기본값 복원"
)

@Composable
fun tr(english: String): String = if (LocalLanguage.current == "ko") korean[english] ?: english else english

@Composable
fun isKorean(): Boolean = LocalLanguage.current == "ko"
