package com.kirinonakar.symvacas.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

/** The saved language is independent of Android's system locale. Math commands remain English. */
val LocalLanguage = staticCompositionLocalOf { "en" }

private val korean = mapOf(
    "Regression equation" to "회귀식",
    "Copy full solution" to "풀이 전체 복사",
    "Select formula" to "수식 선택",
    "Save SVG" to "SVG 저장", "Save PNG" to "PNG 저장", "Graph saved" to "그래프를 저장했습니다",
    "Some intermediate steps were omitted to keep the explanation manageable. The computed result is unchanged." to "풀이가 지나치게 길어지지 않도록 일부 중간 단계를 생략했습니다. 계산 결과에는 영향이 없습니다.",
    "General power rule" to "밑과 지수가 변하는 거듭제곱의 미분",
    "When the exponent also varies, differentiate both the base and exponent using the logarithmic power rule." to "지수도 변수에 따라 달라지면 로그 미분을 이용하여 밑과 지수를 모두 미분합니다.",
    "Separate parameter cases" to "매개변수 값에 따라 경우 나누기",
    "Parameters are constant with respect to the integration variable. Treat exceptional values separately before dividing by a parameter." to "매개변수는 적분 변수에 대한 상수입니다. 매개변수로 나누기 전에 예외 값을 따로 처리합니다.",
    "Integrate each parameter case" to "각 매개변수 조건에서 적분",
    "The displayed antiderivative applies under this parameter condition; its derivative has been checked against the integrand." to "표시된 원시함수는 이 매개변수 조건에서 성립합니다. 미분하여 피적분 함수와 일치하는지 확인했습니다.",
    "Substitute a power of the variable" to "미지수의 거듭제곱을 치환",
    "All nonconstant powers share a common exponent. Replace that power with a new variable to reduce the polynomial's degree." to "상수항을 제외한 모든 항의 지수에 공통 약수가 있습니다. 이 거듭제곱을 새 미지수로 치환하여 차수를 낮춥니다.",
    "Solve the reduced polynomial" to "차수를 낮춘 방정식 풀기",
    "Solve the lower-degree equation for the new variable before returning to the original variable." to "새 미지수에 대한 낮은 차수의 방정식을 풀고 원래 미지수로 돌아갑니다.",
    "Recover roots of the original variable" to "원래 미지수의 근 구하기",
    "For each value of the new variable, take all complex roots of the displayed power equation. The index k is an integer in the displayed range; the final answer applies the original domain restrictions." to "새 미지수의 각 값에 대해 표시된 거듭제곱 방정식의 모든 복소근을 구합니다. k는 표시된 범위의 정수이며, 최종 해에는 원래 정의역 조건을 적용합니다.",
    "Form the characteristic equation" to "특성방정식 세우기",
    "For a homogeneous second-order linear equation with constant coefficients, try an exponential solution. Its exponent satisfies this quadratic equation." to "상수 계수의 이계 동차 선형 미분방정식에 지수함수 형태의 해를 대입합니다. 지수는 이 이차방정식을 만족합니다.",
    "Characteristic roots" to "특성근 구하기",
    "Solve the characteristic quadratic to find the exponents of the independent solutions." to "특성 이차방정식을 풀어 서로 독립인 해의 지수를 구합니다.",
    "Build the homogeneous solution" to "동차방정식의 일반해 구성",
    "Distinct roots give two exponential solutions. For a repeated root, multiply one exponential solution by the independent variable. The arbitrary constants describe the general solution." to "서로 다른 특성근은 두 지수함수 해를 만듭니다. 중근이면 한 지수함수에 독립변수를 곱하여 두 번째 해를 얻습니다. 임의의 상수로 일반해를 나타냅니다.",
    "Rationalize with the conjugate" to "켤레식으로 유리화",
    "Multiply the numerator and denominator by the conjugate. The difference of squares removes the square-root difference on nearby allowed values." to "분자와 분모에 켤레식을 곱합니다. 제곱의 차를 이용하여 주변의 허용된 값에서 제곱근의 차를 없앱니다.",
    "L'Hôpital's rule for infinity/infinity" to "무한대/무한대 꼴에 로피탈 정리 적용",
    "For this differentiable infinity/infinity form, differentiate the numerator and denominator separately along the same approach. The transformed limit has been checked." to "미분 가능한 무한대/무한대 꼴에서 분자와 분모를 따로 미분하고 같은 방향으로 접근합니다. 변환한 극한이 결과와 일치하는지 확인했습니다.",
    "Evaluate the one-sided limit" to "선택한 방향의 한쪽 극한 계산",
    "Use the expression on the selected side of the point. A two-sided limit exists only when the left and right limits agree." to "목표 값의 선택한 쪽에서 식을 계산합니다. 양쪽 극한은 좌극한과 우극한이 같을 때만 존재합니다.",
    "Bound the oscillating factor" to "진동하는 인수의 범위 확인",
    "For a real argument, sine and cosine lie between −1 and 1. Bound the absolute value of the product by its remaining multiplier." to "실수 입력에서 사인과 코사인은 −1과 1 사이입니다. 곱의 절댓값을 나머지 인수의 절댓값으로 제한합니다.",
    "Squeeze theorem" to "샌드위치 정리 적용",
    "The absolute-value bound tends to zero, so the bounded expression also tends to zero along the selected approach." to "절댓값의 상한이 0으로 수렴하므로 원래 식도 선택한 접근 방향에서 0으로 수렴합니다.",
    "Expand near the approach point" to "목표 값 근처에서 급수 전개",
    "Use a local series after expressing the selected approach as h tending to 0 from the right. The remainder records the omitted higher powers." to "선택한 접근 방향을 h가 오른쪽에서 0으로 접근하는 형태로 바꾸고 급수로 전개합니다. 나머지항은 생략된 높은 차수의 항을 나타냅니다.",
    "Use the leading term" to "첫 번째 0이 아닌 항으로 극한 계산",
    "The first nonzero term determines this limit; higher powers vanish relative to it. Both sides are checked for a two-sided approach." to "첫 번째 0이 아닌 항이 극한을 결정하고, 더 높은 차수의 항은 이에 비해 작아집니다. 양쪽 접근이면 두 방향을 모두 확인합니다.",
    "Descriptive statistics" to "기술통계", "Metric" to "항목", "Value" to "값",
    "Mean" to "평균", "Median" to "중앙값", "Variance" to "분산", "Standard deviation" to "표준편차", "Sum" to "합계", "Quartiles" to "사분위수",
    "Covariance" to "공분산", "Correlation" to "상관계수", "One-sample t test" to "단일표본 t 검정", "Welch t test" to "Welch t 검정",
    "Paired t test" to "대응표본 t 검정", "One-sample z test" to "단일표본 z 검정", "Two-sample z test" to "두 표본 z 검정",
    "χ² independence test" to "χ² 독립성 검정", "Fisher exact test" to "Fisher 정확 검정", "Pairwise comparisons" to "쌍별 비교",
    "Comparison" to "비교", "Mean difference" to "평균 차이", "Adjusted p value" to "보정 p값",
    "P-value adjustment" to "p값 다중비교 보정", "Components" to "주성분 요약", "Component" to "주성분", "Feature" to "변수",
    "Feature scaling" to "변수 중심·척도", "Fold scores" to "폴드별 평가", "Fold" to "폴드", "Cluster" to "군집",
    "Lower" to "하한", "Upper" to "상한", "Copy result includes all rows." to "결과 복사에는 모든 행이 포함됩니다.",
    "Kolmogorov–Smirnov test" to "Kolmogorov–Smirnov 검정", "Bootstrap confidence interval" to "부트스트랩 신뢰구간",
    "Bayesian proportion" to "베이지안 비율", "Bayesian mean" to "베이지안 평균", "Bayesian rate" to "베이지안 발생률",
    "n" to "표본 수 n", "sum" to "합계", "mean" to "평균", "median" to "중앙값", "population variance" to "모분산",
    "population SD" to "모표준편차", "sample variance" to "표본분산", "sample SD" to "표본표준편차", "quartiles (inclusive)" to "사분위수 (포함 방식)",
    "p value" to "p값", "confidence interval" to "신뢰구간", "confidence level" to "신뢰수준", "margin of error" to "오차 한계",
    "sample mean" to "표본평균", "mean difference" to "평균 차이", "raw p" to "원래 p값", "adjusted p" to "보정 p값", "reject (1=yes)" to "기각 (1=예)",
    "coefficients" to "계수", "term" to "항", "estimate" to "추정값", "CI95" to "95% 신뢰구간", "exp(coef)" to "지수화 계수",
    "eigenvalues" to "고유값", "explained variance ratio" to "설명 분산 비율", "loadings" to "주성분 적재량", "scores" to "주성분 점수",
    "centers" to "변수 중심", "scales" to "변수 척도", "centroids" to "군집 중심", "labels (1-based)" to "군집 번호 (1부터)",
    "data" to "대치 데이터", "fill values" to "대치 값", "imputed cells" to "대치 셀 수",
    "out-of-fold predictions" to "교차검증 예측값", "out-of-fold probabilities" to "교차검증 예측확률", "fold MSE" to "폴드 MSE", "fold log loss" to "폴드 로그 손실",
    "Combine antiderivatives" to "원시함수 정리",
    "Put the integrated terms and constant multipliers together." to "각 항의 적분 결과와 상수배를 합쳐 원시함수를 정리합니다.",
    "Formal derivative" to "정의되지 않은 함수의 형식적 미분",
    "This function is unspecified. Its derivative remains symbolic until a formula for the function is supplied." to "이 함수의 구체적인 식이 주어지지 않았습니다. 함수식을 지정하기 전까지 도함수는 미분 기호로 나타냅니다.",
    "Evaluate the continuous extension" to "주변에서 정리한 식으로 극한 계산",
    "The original expression is undefined at the point. Use its simplified form on nearby allowed values to find the limit." to "원래 식은 목표 값에서 정의되지 않습니다. 주변의 허용된 값에서 같은 값을 갖는 간단한 식을 사용하여 극한을 구합니다.",
    "Differentiation" to "미분 풀이", "Integration" to "적분 풀이", "Limits" to "극한 풀이",
    "Computed result" to "계산 결과", "Differentiate the expression" to "미분할 식 확인",
    "Constant rule" to "상수의 미분", "Variable rule" to "미지수의 미분", "Sum rule" to "합의 미분법",
    "Constant multiple rule" to "상수배의 미분법", "Quotient rule" to "몫의 미분법", "Product rule" to "곱의 미분법",
    "Power and chain rules" to "거듭제곱과 합성함수의 미분법", "Function and chain rules" to "함수와 합성함수의 미분법",
    "Evaluate this derivative" to "이 부분의 미분 계산", "Differentiate again" to "한 번 더 미분", "Combine the derivatives" to "미분한 항 정리",
    "Integrate the expression" to "적분할 식 확인", "Integration by parts" to "부분적분",
    "Reduce to a special-function integral" to "특수함수로 나타낼 수 있는 적분으로 변환", "Dilogarithm identity" to "이중로그 함수의 적분 관계",
    "Integrate term by term" to "항별로 적분", "Take out the constant" to "상수배를 적분 밖으로 꺼내기",
    "Substitution rule" to "치환적분", "Return to the original variable" to "원래 변수로 되돌리기", "Rewrite the integrand" to "적분할 식 변형",
    "Integral power rule" to "거듭제곱의 적분법", "Logarithm integral rule" to "로그가 되는 적분법", "Standard integral rule" to "기본 적분 공식 적용",
    "Evaluate at the bounds" to "적분 구간의 끝값 대입", "Add the integration constant" to "적분상수 더하기",
    "Identify the approach" to "극한의 접근 방향 확인", "Direct substitution" to "직접 대입", "Cancel a removable factor" to "약분 가능한 인수 제거",
    "L'Hôpital's rule for 0/0" to "0/0 꼴에 로피탈 정리 적용", "Compare highest powers" to "최고차항 비교",
    "Known real roots (partial)" to "확인된 실수 근 · 전체 해는 아님", "Find a numerical root" to "이 구간에서 수치 근 찾기", "Try a starting value" to "초깃값으로 수치 풀이 시도",
    "Numerical real roots (partial)" to "근사 실수 근 · 전체 해는 아님",
    "Automatic real-root search interval: [−10, 10]. Displayed roots are approximate partial results; roots outside this range, missed roots and complex roots may exist. Use nsolve to search another interval." to "실수 근 자동 탐색 구간: [−10, 10]. 표시된 근은 근삿값이며 전체 해가 아닙니다. 범위 밖의 근, 탐색에서 놓친 근, 복소수 근이 더 있을 수 있습니다. 다른 구간은 nsolve로 탐색하세요.",
    "A complete symbolic solution was not found." to "기호식으로 전체 해를 구하지 못했습니다.",
    "The known roots are partial results. Other real or complex roots may exist. Use numerical solving on a continuous interval or try a different starting value." to "표시된 근은 확인된 일부 해입니다. 다른 실수 또는 복소수 해가 더 있을 수 있습니다. 식이 연속인 구간에서 수치 풀이를 시도하거나 초깃값을 바꿔 보세요.",
    "An antiderivative was not found. This does not prove that no closed form exists. For a numerical value, supply a finite integration interval." to "원시함수를 구하지 못했습니다. 이것이 닫힌 형태의 해가 없다는 증명은 아닙니다. 수치 값을 구하려면 유한한 적분 구간을 지정하세요.",
    "Numerical integration needs bounds in the integrand's domain. Check discontinuities and singularities before choosing an interval." to "수치 적분 구간은 함수의 정의역 안에 있어야 합니다. 구간을 정하기 전에 불연속점과 특이점이 있는지 확인하세요.",
    "This answer uses the dilogarithm Li₂, a special function, on the positive real branch." to "이 결과는 양의 실수 구간에서 특수함수인 이중로그 함수 Li₂를 사용합니다.",
    "The complex terms combine to a real antiderivative for x > 0. Differentiating the answer gives the original integrand." to "x > 0에서는 복소수 항들이 합쳐져 실수 원시함수가 됩니다. 이 결과를 미분하면 원래 적분할 함수가 나옵니다.",
    "Choose a suggestion to fill the input, then press Solve or =. Numerical convergence is not guaranteed." to "제안을 누르면 입력란에 수식이 채워집니다. 이후 풀기 또는 =를 누르세요. 수치 풀이의 수렴은 보장되지 않습니다.",
    "A detailed derivation is not available for this expression. The computed result is shown below." to "이 식의 상세 풀이는 아직 지원하지 않습니다. 아래에 계산 결과를 표시합니다.",
    "Find how the expression changes with respect to the selected variable." to "선택한 변수에 따라 식이 얼마나 변하는지 구합니다.",
    "A value that does not depend on the variable has derivative 0." to "이 변수와 관계없는 상수는 변수의 값이 바뀌어도 변하지 않으므로 미분하면 0입니다.",
    "The derivative of the variable with respect to itself is 1." to "변수 자체는 1만큼 늘 때 값도 1만큼 늘므로 자기 자신에 대한 미분은 1입니다.",
    "Differentiate each term separately, then add the derivatives." to "각 항을 따로 미분한 뒤 결과를 더합니다.",
    "Keep the constant multiplier and differentiate the remaining expression." to "상수배는 그대로 두고 나머지 식을 미분합니다.",
    "Differentiate the numerator times the denominator, subtract the numerator times the derivative of the denominator, and divide by the denominator squared." to "분자의 미분에 분모를 곱한 값에서 분자에 분모의 미분을 곱한 값을 뺍니다. 이를 분모의 제곱으로 나누면 몫의 미분이 됩니다.",
    "Differentiate one factor at a time while keeping the other factors, then add the terms." to "한 번에 한 인수만 미분하고 나머지는 그대로 둡니다. 이렇게 얻은 항을 모두 더합니다.",
    "Multiply by the exponent, reduce the exponent by 1, then multiply by the derivative of the inner expression." to "지수를 앞으로 곱하고 지수를 1 줄입니다. 밑이 합성된 식이면 그 안쪽 식의 미분도 곱합니다.",
    "Differentiate the outer function, keep its inner expression, and multiply by the derivative of that inner expression." to "안쪽 식은 유지한 채 바깥 함수를 미분하고, 안쪽 식의 미분을 곱합니다.",
    "The symbolic differentiator evaluates this part directly." to "이 부분은 기호 미분으로 직접 계산합니다.",
    "For a higher derivative, apply the differentiation rules to the previous result." to "고계도함수를 구하려면 앞서 구한 도함수를 다시 미분합니다.",
    "Combine the terms obtained from the rules to simplify the derivative." to "미분법으로 구한 항을 합치고 정리하여 도함수를 간단히 나타냅니다.",
    "Find an antiderivative whose derivative is the integrand." to "미분하면 적분할 함수가 되는 원시함수를 찾습니다.",
    "Choose the logarithm as u and integrate the rational factor as dv. Use ∫u dv = uv − ∫v du." to "로그를 u로 놓고 유리함수 부분을 dv로 선택합니다. 부분적분 공식 ∫u dv = uv − ∫v du를 적용합니다.",
    "The remaining integral of atan(x)/x is expressed using the dilogarithm Li₂, rather than elementary functions." to "남은 atan(x)/x의 적분은 초등함수 대신 이중로그 함수 Li₂를 사용하여 나타냅니다.",
    "The derivative of Li₂(z) is −ln(1−z)/z. Express atan(x) as a difference of complex logarithms to integrate the remaining term." to "Li₂(z)의 미분은 −ln(1−z)/z입니다. atan(x)를 복소 로그의 차로 나타내면 이 관계를 사용하여 남은 항을 적분할 수 있습니다.",
    "The integral of a sum is the sum of the integrals. Work on each term separately." to "합의 적분은 각 항을 적분한 값의 합입니다. 항을 나누어 각각 적분합니다.",
    "A multiplier that does not depend on the integration variable can be taken outside the integral." to "적분 변수와 관계없는 상수배는 적분 기호 밖으로 꺼낼 수 있습니다.",
    "Introduce a new variable for the inner expression. Its derivative changes dx to du, giving a simpler integral." to "안쪽 식을 새 변수로 치환합니다. 그 식의 미분을 이용하여 dx를 du로 바꾸면 더 간단한 적분이 됩니다.",
    "Replace the temporary variable with its original expression." to "임시 변수에 처음 치환한 식을 다시 넣어 원래 변수로 나타냅니다.",
    "Choose u and dv, then use ∫u dv = uv − ∫v du to replace a product integral with a simpler one." to "u와 dv를 선택한 뒤 ∫u dv = uv − ∫v du를 적용합니다. 곱의 적분을 더 간단한 적분으로 바꾸기 위한 방법입니다.",
    "Rewrite the expression into an equivalent form with a familiar integration rule." to "식의 값은 유지하면서 기본 적분 공식을 적용하기 쉬운 형태로 바꿉니다.",
    "Increase the exponent by 1 and divide by that new exponent. The exponent −1 uses the logarithm rule instead." to "지수를 1 늘리고 새 지수로 나눕니다. 지수가 −1이면 이 방법 대신 로그가 되는 적분법을 사용합니다.",
    "Use the standard antiderivative for this expression; differentiating it gives the integrand." to "이 식의 기본 원시함수 공식을 사용합니다. 결과를 미분하면 원래 적분할 함수가 됩니다.",
    "For a continuous integrand, use F(b) − F(a). Singularities require a separate improper-integral check." to "함수가 연속인 구간에서는 원시함수에 끝값을 대입하여 F(b) − F(a)를 계산합니다. 특이점이 있으면 이상적분을 별도로 확인해야 합니다.",
    "Antiderivatives that differ by a constant have the same derivative, so the general answer includes C." to "상수만 다른 원시함수들은 미분하면 같은 함수가 됩니다. 따라서 일반적인 답에는 적분상수 C를 더합니다.",
    "Follow the selected approach to the point. Left and right limits may differ." to "선택한 방향에서 목표 값에 접근합니다. 왼쪽에서의 극한과 오른쪽에서의 극한은 서로 다를 수 있습니다.",
    "When the expression is continuous at the approach point, substitute the point directly." to "목표 값에서 식이 연속이면 그 값을 직접 대입하여 극한을 구할 수 있습니다.",
    "Cancel common factors away from the approach point. The simplified expression has the same limit there." to "목표 값 자체를 제외한 주변에서 공통 인수를 약분합니다. 약분한 식도 같은 극한값을 갖습니다.",
    "For this differentiable 0/0 form, differentiate the numerator and denominator separately, then evaluate their ratio along the same approach." to "로피탈 정리를 적용할 수 있는 이 0/0 꼴에서는 분자와 분모를 각각 미분합니다. 이후 같은 방향에서 미분한 식의 비에 대한 극한을 구합니다.",
    "For a rational function at infinity, the highest powers determine whether the ratio tends to 0, a finite coefficient ratio, or infinity." to "유리함수의 무한대에서의 극한은 최고차항으로 판단합니다. 차수를 비교하면 0, 최고차항 계수의 비 또는 무한대로 향하는지 알 수 있습니다.",
    "The result keeps the original domain and the selected calculus settings." to "원래 식의 정의역과 선택한 미적분 조건을 유지한 계산 결과입니다.",
    "Step-by-step solution" to "단계별 풀이",
    "Remove computation limit" to "계산 제한 해제",
    "Disables app time, workload, input size and exponent limits. Result size and precision settings stay unchanged; manual cancellation remains available." to "앱의 시간·계산량·입력 크기·지수 제한을 해제합니다. 결과 길이와 정밀도 설정은 그대로 유지하며 수동 취소할 수 있습니다.",
    "Calc mode step by step" to "계산기 모드 단계별 풀이",
    "Introduce a new variable to remove the squared term. The cubic becomes simpler to solve." to "새 미지수로 치환하여 이차항을 없앱니다. 그러면 삼차방정식을 더 간단한 형태로 풀 수 있습니다.",
    "Collect the transformed equation into t³ + pt + q = 0, using the new variable chosen above." to "위에서 정한 새 미지수를 사용하여 t³ + pt + q = 0 형태로 정리합니다.",
    "Calculate (q/2)² + (p/3)³. This determines the square root used in Cardano's formula." to "(q/2)² + (p/3)³를 계산합니다. 이 값은 카르다노 공식에서 제곱근 안에 들어갑니다.",
    "Write the new variable as the sum of two values. Their product must satisfy the displayed constraint." to "새 미지수를 두 값의 합으로 놓습니다. 두 값의 곱은 표시된 조건을 만족해야 합니다.",
    "Choose cube roots of the two displayed quantities while keeping the required product. Arbitrary cube-root pairs do not always give a solution." to "표시된 두 값의 세제곱근을 고르되 곱의 조건을 유지합니다. 세제곱근을 아무렇게나 짝지으면 해가 되지 않을 수 있습니다.",
    "Use the original substitution to convert back to the variable in the input equation." to "처음 치환한 관계를 사용하여 입력한 방정식의 미지수로 되돌립니다.",
    "Move the constant and divide by the variable coefficient in each candidate branch." to "각 해의 후보에서 상수를 이항하고 미지수의 계수로 나눕니다.",
    "Apply the exponential function to undo the logarithm, then check the original logarithm's domain." to "지수함수를 적용하여 로그를 없앤 뒤 원래 로그의 정의역 조건을 확인합니다.",
    "Divide by the derivative's coefficient to put the equation in the form y′ + p(t)y = q(t)." to "미분항의 계수로 양변을 나누어 y′ + p(t)y = q(t) 형태로 정리합니다.",
    "Multiply both sides by the integrating factor. The product rule turns the left side into a single derivative." to "양변에 적분인자를 곱합니다. 곱의 미분법을 사용하면 좌변을 하나의 미분으로 묶을 수 있습니다.",
    "Integrate the product derivative and the right-hand side. Include an arbitrary constant for the general solution." to "곱의 미분과 우변을 각각 적분합니다. 일반해에는 적분상수를 포함합니다.",
    "Divide by the integrating factor to leave the unknown function by itself." to "양변을 적분인자로 나누어 구하려는 함수만 남깁니다.",
    "Use the supplied values of the function to determine the integration constants." to "주어진 함수의 값을 대입하여 적분상수를 결정합니다.",
    "These excluded values still apply even if the simplified equation no longer contains the original denominator." to "정리한 식에서 원래 분모가 사라져도 제외해야 하는 값의 조건은 그대로 적용됩니다.",
    "Substitution method" to "기본 풀이 · 대입법",
    "Elimination method" to "기본 풀이 · 소거법",
    "Advanced solution · Gaussian elimination" to "고급 풀이 · 가우스 소거법",
    "Rearrange the first equation" to "첫 번째 방정식 정리",
    "Subtract {term} from both sides." to "양변에서 {term}를 뺍니다.",
    "Add {term} to both sides." to "양변에 {term}를 더합니다.",
    "Divide both sides by {coefficient}." to "양변을 {coefficient}로 나눕니다.",
    "Multiply both sides by −1." to "양변에 −1을 곱합니다.",
    "Combine like terms." to "동류항을 정리합니다.",
    "Use this expression in the other equation." to "이 식을 다른 방정식에 대입합니다.",
    "The variable is already isolated." to "이미 미지수의 값이 구해진 형태입니다.",
    "Read the solution from the matrix" to "행렬에서 해 읽기",
    "Each pivot row gives one variable's value in the last column. Read the values in the displayed variable order." to "각 기준 행의 마지막 열이 해당 미지수의 값입니다. 표시된 미지수 순서에 따라 값을 읽습니다.",
    "Read each pivot variable in terms of the variables without pivots. Those variables are free, so there are infinitely many solutions." to "기준 열이 있는 미지수를 나머지 미지수로 나타냅니다. 기준 열이 없는 미지수는 자유변수이므로 해가 무수히 많습니다.",
    "A row has zero variable coefficients but a nonzero constant. It represents a false equality, so there is no solution." to "미지수 계수는 모두 0인데 상수가 0이 아닌 행이 있습니다. 참일 수 없는 등식이므로 해가 없습니다.",
    "Substitute into the second equation" to "두 번째 방정식에 대입",
    "Solve the equation with one unknown" to "미지수가 하나인 방정식 풀기",
    "Calculate the remaining variable" to "나머지 변수 계산",
    "The equations describe the same relation" to "두 방정식이 같은 관계를 나타냄",
    "The equations conflict" to "방정식이 서로 모순됨",
    "Collect variable terms on the left" to "미지수 항을 좌변에 모으기",
    "Eliminate one variable" to "미지수 하나를 소거",
    "Back-substitute into an earlier equation" to "앞의 방정식에 역으로 대입",
    "Some variables are free" to "자유롭게 정할 수 있는 변수가 있음",
    "Scale the pivot row" to "피벗 행 전체에 같은 수를 곱하기",
    "Move the other terms to the opposite side and divide by the coefficient. We can then replace this variable in the other equation." to "다른 항을 반대쪽으로 이항한 뒤 계수로 나눕니다. 이렇게 미지수 하나를 정리하면 다른 방정식에 대입할 수 있습니다.",
    "Replace the isolated variable with its expression. The second equation now has only one unknown." to "정리한 미지수 자리에 그 식을 넣습니다. 그러면 두 번째 방정식에 미지수가 하나만 남습니다.",
    "Combine like terms, move the constant to the right, and divide by the coefficient to find the first value." to "동류항을 합치고 상수를 우변으로 옮긴 뒤 계수로 나누면 첫 번째 값을 구할 수 있습니다.",
    "Put the value we found back into the rearranged first equation to find the other variable." to "구한 값을 정리해 둔 첫 번째 방정식에 대입하면 나머지 미지수의 값도 구할 수 있습니다.",
    "Substitution gives an identity. One variable can be chosen freely, and the other follows from the first equation." to "대입한 결과가 항상 참인 항등식입니다. 한 변수를 자유롭게 정하면 다른 변수는 첫 번째 방정식으로 구할 수 있습니다.",
    "Substitution gives a false equality. No values can satisfy both equations at once." to "대입한 결과가 참일 수 없는 등식입니다. 두 방정식을 동시에 만족하는 값은 없으므로 해가 없습니다.",
    "Put matching variables on the same side so we can combine equations and remove one unknown at a time." to "같은 미지수의 항을 같은 쪽에 모읍니다. 방정식을 더하거나 빼서 미지수를 하나씩 없애기 위한 준비입니다.",
    "Subtract a suitable multiple of another equation so one variable disappears. This leaves fewer unknowns to solve." to "다른 방정식에 알맞은 수를 곱한 뒤 빼면 미지수 하나가 없어집니다. 남은 미지수가 줄어들어 더 쉽게 풀 수 있습니다.",
    "Elimination gives a false equality. No values can satisfy all the equations at once." to "소거한 결과가 참일 수 없는 등식입니다. 모든 방정식을 동시에 만족하는 값은 없으므로 해가 없습니다.",
    "Start with the equation with the fewest unknowns. Substitute each value into earlier equations to find the remaining variables." to "미지수가 가장 적게 남은 방정식부터 풉니다. 구한 값을 앞의 방정식에 차례로 대입하여 나머지 변수를 구합니다.",
    "The independent equations do not determine every variable. Free variables describe the family of solutions." to "서로 독립인 방정식이 부족하여 모든 변수가 하나의 값으로 정해지지 않습니다. 자유변수를 사용하여 해 전체를 나타냅니다.",
    "The columns follow the variable order shown below; the last column contains the constants." to "열은 아래에 표시한 미지수 순서대로 나열합니다. 세로선 오른쪽 마지막 열은 방정식 우변의 상수입니다.",
    "Swap the whole equations to place a nonzero coefficient in the pivot position." to "계수가 0이 아닌 방정식을 기준으로 삼기 위해 두 행 전체를 서로 바꿉니다.",
    "Multiply every entry in this row by the same number so the pivot coefficient becomes 1." to "이 행의 모든 값에 같은 수를 곱하여 기준이 되는 계수를 1로 만듭니다.",
    "Subtract a multiple of the pivot row from the entire other row. Its entry in this column becomes 0." to "다른 행 전체에서 기준 행의 배수를 뺍니다. 그러면 이 열의 계수가 0이 되어 해당 미지수가 없어집니다.",
    "Subtract the right-hand side from both sides. The equation now has 0 on the right, which makes its structure easier to see." to "양변에서 우변의 식을 뺍니다. 우변을 0으로 만들면 방정식의 형태를 파악하기 쉽습니다.",
    "Expand products and combine terms with the same power of the variable." to "곱을 전개하고 미지수의 차수가 같은 항끼리 합칩니다.",
    "Subtract the constant from both sides, leaving the variable term on the left." to "양변에서 상수를 빼서 좌변에는 미지수 항만 남깁니다.",
    "Divide both sides by the same nonzero coefficient to leave the variable by itself." to "양변을 0이 아닌 같은 계수로 나누면 미지수의 값을 구할 수 있습니다.",
    "For ax² + bx + c = 0, calculate D = b² − 4ac. This is the quantity under the square root in the quadratic formula." to "ax² + bx + c = 0에서 D = b² − 4ac를 계산합니다. 이 값은 근의 공식에서 제곱근 안에 들어갑니다.",
    "Substitute a, b, c and D into x = (−b ± √D)/(2a). The two signs give the candidate roots." to "a, b, c와 D를 근의 공식 x = (−b ± √D)/(2a)에 넣습니다. 더하기와 빼기를 각각 적용하여 해의 후보를 구합니다.",
    "Division by zero is undefined. Keep this restriction when removing the denominator so invalid roots are not included." to "0으로 나누는 것은 정의되지 않습니다. 분모를 없앤 뒤에도 이 조건을 유지하여 잘못된 해를 제외합니다.",
    "Multiply both sides by the denominator. This is valid only where the denominator is nonzero." to "양변에 분모를 곱합니다. 분모가 0이 아닌 경우에만 가능한 연산입니다.",
    "Rewrite the polynomial as a product. A product is zero when at least one factor is zero." to "다항식을 곱의 형태로 바꿉니다. 곱이 0이려면 적어도 한 인수가 0이어야 합니다.",
    "Solve the smaller equations separately, then combine their allowed roots." to "각 인수의 간단한 방정식을 따로 풀고 조건을 만족하는 근을 모읍니다.",
    "Move the constant and divide by the variable coefficient in this factor." to "이 인수에서 상수를 이항하고 미지수의 계수로 나누어 근을 구합니다.",
    "Discard candidates excluded by the original equation, denominators or variable assumptions." to "원래 방정식, 분모의 조건 또는 미지수의 가정을 만족하지 않는 후보는 제외합니다.",
    "These are the solver's final values after applying the original equation and domain restrictions." to "원래 방정식과 정의역 조건을 반영한 최종 해입니다.",
    "Use the starting value or interval to find a nearby root numerically." to "초깃값 또는 탐색 구간을 이용하여 근처의 근을 수치적으로 구합니다.",
    "Put the computed value into the left side minus the right side. A residual near zero checks that it satisfies the equation numerically." to "구한 값을 좌변에서 우변을 뺀 식에 대입합니다. 잔차가 0에 가까우면 수치적으로 방정식을 만족하는지 확인할 수 있습니다.",
    "Move and divide the other terms so the function is alone on one side." to "다른 항을 이항하고 계수로 나누어 한쪽에는 함수 항만 남깁니다.",
    "Apply the inverse function to get a principal value. Periodic functions can have more solutions, so this is only the first candidate." to "역함수를 적용하여 주값을 구합니다. 주기함수는 다른 해도 가질 수 있으므로 이 값은 첫 번째 후보입니다.",
    "Add the function's periods to include all candidate branches before applying domain restrictions." to "함수의 주기를 더하여 해의 후보 전체를 나타냅니다. 이후 정의역 조건을 적용합니다.",
    "Choose this factor so the left side becomes the derivative of a product, which can be integrated directly." to "좌변을 곱의 미분 형태로 만들 수 있는 인자를 선택합니다. 그러면 양변을 적분할 수 있습니다.",
    "Normalize the first-order linear equation" to "일계 선형 미분방정식의 표준형으로 정리",
    "Integrating factor" to "적분인자 구하기",
    "Multiply by the integrating factor" to "양변에 적분인자를 곱하여 곱의 미분으로 정리",
    "Integrate both sides" to "양변 적분",
    "Solve for the dependent function" to "종속함수에 대해 정리",
    "Isolate the function" to "함수 항을 한쪽으로 모으기",
    "Exponentiate both sides" to "양변에 지수함수 적용",
    "Principal inverse value" to "역함수의 주값 구하기",
    "Include periodic branches (n is an integer)" to "주기성을 반영한 해의 후보 (n은 정수)",
    "Isolate the variable in each branch" to "각 해의 후보에서 미지수 정리",
    "Expanded" to "펼쳐짐", "Collapsed" to "접힘",
    "Original equation" to "입력한 방정식",
    "Isolate the root" to "근호가 있는 항만 남기기",
    "Raise both sides to the root index" to "양변을 근지수만큼 거듭제곱",
    "Simplify the powered equation" to "거듭제곱한 식 정리",
    "Check candidates in the original equation" to "원래 방정식에 후보 대입하여 확인",
    "Move the other terms and divide by the nonzero coefficient so the root is alone on one side." to "다른 항을 이항하고 0이 아닌 계수로 나누어 한쪽에 근호가 있는 항만 남깁니다.",
    "Raise both sides to the displayed integer power to remove the root. This can introduce extra candidates, so check them in the original equation." to "근호를 없애기 위해 양변을 표시된 정수 지수로 거듭제곱합니다. 원래 식의 해가 아닌 후보가 생길 수 있으므로 원래 방정식에 대입하여 확인합니다.",
    "The root followed by its integer power gives the radicand. Evaluate the same power on the other side." to "근호가 있는 항을 근지수만큼 거듭제곱하면 근호 안의 식이 남습니다. 반대쪽의 거듭제곱도 계산합니다.",
    "Substitute each candidate into the original equation. Keep only values that satisfy it and its original domain restrictions." to "각 후보를 원래 방정식에 대입합니다. 원래 식과 정의역 조건을 모두 만족하는 값만 해로 남깁니다.",
    "Move all terms to the left" to "모든 항을 좌변으로 이항",
    "Expand and collect like terms" to "식을 전개하고 동류항 정리",
    "Move the constant to the right" to "상수항을 우변으로 이항",
    "Divide by the coefficient of the variable" to "미지수의 계수로 양변 나누기",
    "Compute the discriminant" to "판별식 계산",
    "Apply the quadratic formula" to "근의 공식 적용",
    "Simplify the candidate roots" to "해의 후보 정리",
    "Evaluate the square root and simplify each fraction to obtain the candidate roots." to "제곱근을 계산하고 각 분수를 정리하여 해의 후보를 구합니다.",
    "Isolate a variable in the linear equation" to "일차방정식에서 한 변수 분리",
    "Rearrange the linear equation so one variable is expressed in terms of the other." to "일차방정식을 정리하여 한 변수를 다른 변수로 나타냅니다.",
    "Substitute into the other equation" to "다른 방정식에 대입",
    "Replace the isolated variable with its expression to obtain an equation with one unknown." to "분리한 변수의 식을 대입하여 미지수가 하나인 방정식을 만듭니다.",
    "Back-substitute each candidate root" to "각 해의 후보를 역대입",
    "Substitute each candidate into the linear relation to find its matching value of the other variable." to "각 해의 후보를 일차방정식에 대입하여 짝이 되는 다른 변수의 값을 구합니다.",
    "Substitution gives an identity. One variable can be chosen freely, and the other follows from the linear equation." to "대입한 결과가 항등식입니다. 한 변수를 자유롭게 정하면 다른 변수는 일차방정식으로 구합니다.",
    "Move the constant and divide by the nonzero variable coefficient." to "상수항을 이항하고 0이 아닌 미지수의 계수로 나눕니다.",
    "Sum and difference method" to "합과 차를 이용한 풀이",
    "Determine the sum of squares and the product" to "제곱의 합과 곱 계산",
    "Treat the sum of squares and the product as two quantities and combine the equations to determine them." to "제곱의 합과 곱을 각각 하나의 양으로 보고 방정식을 결합하여 구합니다.",
    "Introduce the sum and difference" to "합과 차로 치환",
    "Use the sum and difference of the two variables as new unknowns." to "두 변수의 합과 차를 새로운 미지수로 놓습니다.",
    "Form the squared sum and difference" to "합과 차의 제곱 전개",
    "Expand the squares of the sum and difference. Their cross terms are twice the product of the original variables." to "합과 차의 제곱을 전개합니다. 교차항은 원래 두 변수의 곱의 두 배입니다.",
    "Substitute the known quadratic values" to "제곱의 합과 곱 대입",
    "Insert the known sum of squares and product, then simplify each squared equation." to "알고 있는 제곱의 합과 곱을 대입하여 각 방정식을 정리합니다.",
    "Take both square-root signs" to "제곱근의 두 부호 고려",
    "Each squared equation gives both square-root signs. Keep every independent combination of these candidates." to "각 제곱식에서 제곱근의 두 부호를 모두 고려합니다. 각 후보의 부호 조합을 모두 남깁니다.",
    "Recover the original variables" to "원래 변수 계산",
    "Add and subtract the sum and difference equations, then divide by two." to "합과 차의 방정식을 더하고 뺀 뒤 2로 나눕니다.",
    "Combine the candidate solution pairs" to "해의 후보 쌍 구성",
    "Use each sum and difference combination to obtain a pair. The final solution applies the original variable and domain restrictions." to "합과 차의 각 조합으로 해의 후보 쌍을 구합니다. 최종 해에는 원래 변수와 정의역 조건을 적용합니다.",
    "Normalize the exponential product" to "지수함수 곱의 방정식 치환",
    "Introduce a scaled and shifted variable so the equation has the form u·exp(u) = z." to "변수를 배율과 이동으로 치환하여 u·exp(u) = z 꼴로 만듭니다.",
    "Rewrite as a Lambert W equation" to "Lambert W 방정식 꼴로 정리",
    "Rearrange the equation into a variable times its own exponential equal to a constant." to "변수와 그 변수의 지수함수의 곱이 상수와 같도록 정리합니다.",
    "Use the Lambert W inverse" to "Lambert W 역함수 사용",
    "Lambert W inverts w·exp(w): each allowed branch satisfies W(z)·exp(W(z)) = z." to "Lambert W는 w·exp(w)의 역함수입니다. 각 허용된 분기는 W(z)·exp(W(z)) = z를 만족합니다.",
    "Apply the allowed Lambert W branches" to "허용된 Lambert W 분기 적용",
    "Use the Lambert W branches returned for the selected domain. Integer branch indices describe the complex family; the real domain retains only allowed real branches." to "선택된 정의역에서 반환된 Lambert W 분기를 사용합니다. 정수 분기 번호는 복소수 해의 집합을 나타내며 실수 정의역에서는 허용된 실수 분기만 남깁니다.",
    "Evaluate the principal real solution" to "주 분기의 실수 해 근삿값 계산",
    "For a nonnegative Lambert W argument, the principal branch gives the unique real solution. Evaluate it numerically." to "Lambert W의 인수가 음수가 아니면 주 분기가 유일한 실수 해를 줍니다. 그 근삿값을 계산합니다.",
    "Check the real Lambert W domain" to "Lambert W의 실수 정의역 확인",
    "A real Lambert W value requires its argument to be at least −1/e. If this condition fails, there is no real solution." to "Lambert W가 실숫값을 가지려면 인수가 −1/e 이상이어야 합니다. 이 조건을 만족하지 않으면 실수 해가 없습니다.",
    "Recover the original variable" to "원래 변수로 복원",
    "Undo the substitution to express each candidate in the original variables." to "치환을 되돌려 각 해의 후보를 원래 변수로 나타냅니다.",
    "The system solver returned a finite set of Lambert W candidates; additional complex branches may exist." to "연립방정식 풀이가 유한한 Lambert W 해의 후보를 반환했습니다. 추가적인 복소수 분기가 있을 수 있습니다.",
    "The exponential factor is nonzero, so only the linear factor can vanish." to "지수함수는 0이 아니므로 일차 인수만 0이 될 수 있습니다.",
    "Exclude zero denominators" to "분모가 0인 값 제외",
    "Multiply by the nonzero denominator" to "0이 아닌 분모를 양변에 곱하기",
    "Factor the polynomial" to "다항식 인수분해",
    "Set each factor equal to zero" to "각 인수를 0으로 놓기",
    "Solve the linear factor" to "일차 인수의 방정식 풀기",
    "Remove the quadratic term" to "치환하여 이차항 제거",
    "Depressed cubic" to "이차항이 없는 삼차방정식",
    "Cardano discriminant" to "카르다노 공식의 판별식 계산",
    "Cardano substitution" to "카르다노 치환과 곱 조건",
    "Choose cube roots satisfying the product constraint" to "곱 조건을 만족하는 세제곱근 선택",
    "Substitute back" to "원래 미지수로 다시 치환",
    "Augmented matrix (variable order)" to "첨가행렬의 미지수 순서",
    "Augmented matrix" to "첨가행렬",
    "Swap rows" to "행 교환",
    "Divide the pivot row" to "피벗 행을 피벗 값으로 나누기",
    "Eliminate the pivot column from another row" to "다른 행에서 피벗 열 소거",
    "Read solutions from the reduced matrix" to "기약행렬에서 해 구하기",
    "Initial guess" to "초깃값", "Initial bracket" to "초기 탐색 구간",
    "Numerical root" to "수치적으로 구한 근",
    "Substitute the root: residual should be near zero" to "근을 대입하여 잔차가 0에 가까운지 확인",
    "Apply initial conditions" to "초기 조건 적용",
    "Identity: every allowed value is a solution" to "항등식: 정의역의 모든 값이 해",
    "Contradiction: there is no solution" to "모순: 해 없음",
    "Assume the leading coefficient is nonzero" to "최고차항의 계수가 0이 아니라고 가정",
    "Check the original domain restrictions" to "원래 식의 정의역 조건 확인",
    "Keep solutions allowed by the original equation and domain" to "원래 방정식과 정의역을 만족하는 해만 선택",
    "Unresolved solution set" to "아직 구하지 못한 해의 조건",
    "Detailed transformations are unavailable for this equation; the steps below summarize the solver input and result." to "이 방정식의 상세 전개는 아직 지원하지 않습니다. 아래에는 입력식과 풀이 결과를 요약합니다.",
    "The equation is too large for a detailed derivation; showing a solver summary." to "상세 풀이를 표시하기에는 식이 너무 큽니다. 풀이 결과를 요약합니다.",
    "Numerical solving finds a root near the initial guess or within the bracket; it does not enumerate all roots." to "수치 풀이는 초깃값 근처 또는 탐색 구간 안의 근 하나를 구합니다. 모든 근을 구하는 것은 아닙니다.",
    "This derivation assumes the leading coefficient is nonzero; degenerate parameter cases require separate solving." to "이 풀이는 최고차항의 계수가 0이 아니라고 가정합니다. 계수가 0이 되는 매개변수 값은 따로 풀어야 합니다.",
    "Bayesian linear regression" to "베이지안 선형 회귀",
    "Bayesian logistic regression" to "베이지안 로지스틱 회귀",
    "Bayesian Two-Sample Comparison" to "베이지안 두 표본 비교",
    "Mean A" to "A 집단 표본 평균",
    "Mean B" to "B 집단 표본 평균",
    "Posterior Mean Difference (B - A)" to "사후 평균 차이 (B - A)",
    "Posterior Effect Size" to "사후 효과크기",
    "difference credible interval" to "평균 차이 신용구간",
    "effect credible interval" to "효과크기 신용구간",
    "difference posterior SD" to "평균 차이 사후 SD",
    "variance model" to "분산 모형",
    "prior mean" to "사전 평균",
    "prior kappa" to "사전 κ",
    "prior alpha" to "분산 사전 α",
    "prior beta" to "분산 사전 β",
    "posterior mean A" to "A 집단 사후 평균",
    "posterior mean B" to "B 집단 사후 평균",
    "credible level" to "신용구간 수준",
    "difference interval method" to "평균 차이 구간 계산법",
    "effect interval method" to "효과크기 구간 계산법",
    "probability MCSE" to "확률 MCSE",
    "effect mean MCSE" to "효과크기 평균 MCSE",
    "difference interval MCSE" to "평균 차이 구간 MCSE (하한·상한)",
    "effect interval MCSE" to "효과크기 구간 MCSE (하한·상한)",
    "posterior samples" to "사후 추출 수",
    "BF method" to "BF 계산법",
    "Prior SD" to "사전분포 SD",
    "Credible level (0–1)" to "사후 확률 수준 (0–1)",
    "Credible interval" to "credible interval",
    "Variance prior shape" to "분산 사전분포 shape",
    "Variance prior scale" to "분산 사전분포 scale",
    "Posterior variance mean" to "사후 분산 평균",
    "Posterior estimate" to "사후 추정값",
    "Posterior SD" to "사후 SD",
    "OR credible interval" to "OR credible interval",
    "Predictive lower" to "예측구간 하한",
    "Predictive upper" to "예측구간 상한",
    "Inference method" to "추론 방법",
    "Conjugate (exact)" to "켤레 사후분포 (정확)",
    "Laplace approximation" to "Laplace 근사",
    "Samples per chain (100–5000)" to "체인별 표본 수 (100–5000)",
    "Warmup (50–5000)" to "Warmup (50–5000)",
    "Max tree depth (1–10)" to "최대 트리 깊이 (1–10)",
    "Chains (2–4)" to "체인 수 (2–4)",
    "Samples per chain" to "체인별 표본 수",
    "Warmup" to "Warmup",
    "Max tree depth" to "최대 트리 깊이",
    "Chains" to "체인 수",
    "Chain" to "체인",
    "Acceptance rate" to "수용률",
    "Divergences" to "발산 수",
    "Step size" to "단계 크기",
    "Model diagnostics" to "모형 진단 요약",
    "Rank-normalized R-hat" to "순위 정규화 R-hat",
    "Bulk ESS" to "Bulk ESS",
    "Tail ESS" to "Tail ESS",
    "Autocorrelation ESS" to "자기상관 ESS",
    "MCSE" to "MCSE",
    "Zero-mean priors include the intercept on standardized predictors; coefficients in original units." to "표준화된 설명변수와 절편에 평균 0 사전분포 적용 · 계수는 원래 단위",
    "NUTS adapts trajectory length; step size adapts during warmup. Check rank-normalized R-hat, bulk/tail ESS and divergences." to "NUTS · 경로 길이 자동 조절 · warmup 중 단계 크기 적응 · rank-normalized R-hat, bulk/tail ESS, 발산 수를 확인하세요.",
    "NUTS posterior samples; check R-hat, ESS and divergences." to "NUTS 사후 표본 · R-hat, ESS, 발산 수를 확인하세요.",
    "Mean acceptance probability" to "평균 수용 확률",
    "Max tree depth hits" to "최대 트리 깊이 도달 횟수",
    "Mean tree depth" to "평균 트리 깊이",
    "Mean leapfrog steps" to "평균 leapfrog 단계 수",
    "NUTS reached max tree depth; increase max tree depth and inspect mixing." to "NUTS가 최대 트리 깊이에 도달했습니다. 최대 깊이를 늘리고 체인 혼합을 확인하세요.",
    "Gaussian Laplace posterior at the MAP; approximate credible intervals." to "MAP에서 Gaussian Laplace 사후분포 근사 · 근사 credible interval",
    "Normal-inverse-gamma posterior; exact Student-t credible intervals." to "Normal-inverse-gamma 사후분포 · 정확한 Student-t credible interval",
    "Training probabilities evaluated at the MAP." to "학습 확률은 MAP 계수에서 계산합니다.",
    "Training predictions evaluated at posterior mean coefficients." to "학습 예측은 사후 평균 계수에서 계산합니다.",
    "NUTS divergences detected; posterior summaries may be unreliable." to "NUTS 발산이 발생했습니다. 사후 요약 결과가 불안정할 수 있습니다.",
    "NUTS rank-normalized R-hat exceeds 1.01 or is unavailable; increase warmup and samples." to "NUTS rank-normalized R-hat이 1.01을 넘거나 계산되지 않습니다. warmup과 표본 수를 늘리세요.",
    "NUTS bulk or tail ESS is below 100 per chain; increase samples and inspect mixing." to "NUTS bulk 또는 tail ESS가 체인당 100 미만입니다. 표본 수를 늘리고 체인 혼합을 확인하세요.",
    "Enter all Bayesian prior and interval parameters" to "베이지안 사전분포·구간 매개변수를 모두 입력하세요",
    "Prior parameters must be positive" to "사전분포 매개변수는 양수여야 합니다",
    "Prior kappa, alpha and beta must be positive" to "사전 κ·α·β는 양수여야 합니다",
    "Credible level must lie in (0,1)" to "베이지안 구간 수준은 0과 1 사이여야 합니다",
    "Proportion threshold must lie in (0,1)" to "기준 비율은 0과 1 사이여야 합니다",
    "Rate threshold must be nonnegative" to "기준 발생률은 0 이상이어야 합니다",
    "Use binary 0/1 observations or nonnegative integer counts" to "0/1 관측값 또는 0 이상 정수 횟수를 입력하세요",
    "Successes must not exceed nonnegative integer trials" to "성공 수는 0 이상 정수 시행 수를 넘을 수 없습니다",
    "Each exposure must be positive" to "각 노출량은 양수여야 합니다",
    "Positive total trials or exposure required" to "총 시행 수·노출량은 양수여야 합니다",
    "Counts must be nonnegative integers; exposure must be nonnegative" to "횟수는 0 이상 정수, 노출량은 0 이상이어야 합니다",
    "Use two columns: successes/trials or count/exposure" to "성공 수·시행 수 또는 횟수·노출량 두 열을 입력하세요",
    "Enter Bayesian observations or a count table" to "베이지안 관측값 또는 빈도표를 입력하세요",
    "Auto columns" to "열 수 자동", "Column count must be between 1 and 100" to "열 개수는 1~100이어야 합니다",
    "Clustered heatmap" to "군집 히트맵", "Single linkage · Euclidean" to "단일 연결 · 유클리드 거리", "Clustering…" to "군집 계산 중…",
    "Orientation" to "방향", "Horizontal" to "가로", "Vertical" to "세로",
    "Violin + points" to "바이올린 + 원자료", "Heat map" to "히트맵", "Correlation heat map" to "상관관계 히트맵",
    "Heat map data" to "히트맵 자료", "Raw values" to "원자료", "Z-score by row" to "행 기준 Z 점수", "Z-score by column" to "열 기준 Z 점수",
    "Correlation" to "상관관계", "Correlation method" to "상관계수 방식", "Pearson (p)" to "Pearson (p)", "Spearman (s)" to "Spearman (s)", "Kendall (k)" to "Kendall (k)",
    "Hierarchical clustering" to "계층 군집", "Fit to screen" to "화면에 맞춤", "X axis variables" to "x축 항목", "Y axis variables" to "y축 항목", "No numeric columns" to "수치 열이 없습니다",
    "Cluster linkage" to "군집 연결법", "Distance metric" to "거리 측도", "Single" to "단일", "Average" to "평균", "Complete" to "완전", "Ward" to "Ward",
    "Euclidean" to "유클리드", "Manhattan" to "맨해튼", "Correlation (1 − r)" to "상관계수 (1 − r)",
    "Cross-validate α (5 folds)" to "α 교차검증(5겹)", "Firth correction" to "Firth 보정", "Auto" to "자동", "Always" to "항상",
    "Use interaction pairs like 1,2;1,3" to "1,2;1,3 형식으로 상호작용 쌍을 입력하세요",
    "Use interaction pairs like age,weight;2,3" to "age,weight;2,3 형식으로 상호작용 쌍을 입력하세요",
    "Interaction columns must be among the selected predictors" to "상호작용 열은 선택한 설명변수 안에서 골라야 합니다",
    "Interaction positions must be within the selected predictors" to "상호작용 순서(p1,p2)는 선택한 설명변수 범위 안이어야 합니다",
    "Unknown interaction column" to "알 수 없는 상호작용 열·이름입니다",
    "Interaction pairs must be distinct" to "상호작용 쌍은 서로 달라야 합니다",
    "Interaction predictors must be among the selected predictors" to "상호작용 변수는 선택한 설명변수 안에서 골라야 합니다",
    "Interactions must be a list of [i,j] predictor pairs" to "상호작용은 [i,j] 설명변수 쌍 목록이어야 합니다",
    "Choose at least one predictor" to "설명변수를 하나 이상 선택하세요",
    "Raw values · rows × columns" to "원자료 · 행 × 열", "Row z-scores · color = z-score" to "행 기준 Z 점수 · 색 = Z 점수", "Column z-scores · color = z-score" to "열 기준 Z 점수 · 색 = Z 점수",
    "Pearson correlation · pairwise complete observations" to "Pearson 상관계수 · 각 열 쌍의 결측값 제외", "Spearman correlation · pairwise complete observations" to "Spearman 상관계수 · 각 열 쌍의 결측값 제외", "Kendall correlation · pairwise complete observations" to "Kendall 상관계수 · 각 열 쌍의 결측값 제외",
    "Rows × columns · color = value" to "행 × 열 · 색 = 값", "Pearson r · pairwise complete observations" to "Pearson r · 각 열 쌍의 결측값 제외",
    "Input source" to "자료 선택", "Current data" to "현재 데이터", "Expression" to "분석 식",
    "Enter data first" to "데이터를 입력하세요", "Choose valid data columns" to "자료 열을 선택하세요", "Choose distinct analysis columns" to "서로 다른 분석 열을 선택하세요",
    "Roles must use different columns" to "각 역할에 서로 다른 열을 선택하세요", "Complete selected rows required" to "선택한 열의 빈 셀을 채우세요", "Choose at least two groups" to "그룹을 둘 이상 선택하세요",
    "Choose at least two conditions" to "조건 열을 둘 이상 선택하세요", "Paired observations require the same two categories" to "대응 관측값에는 공통된 두 범주가 필요합니다",
    "The count table needs exactly two rows" to "빈도표는 정확히 두 행이어야 합니다", "Enter the event value" to "사건 발생 값을 입력하세요", "Event column must have at most two values" to "사건 열에는 두 종류 이하의 값이 필요합니다",
    "Event value does not occur in the selected column" to "선택한 사건 열에 해당 값이 없습니다", "Log-rank requires exactly two groups" to "로그순위 검정은 두 그룹이 필요합니다",
    "Advanced analysis" to "고급 분석", "Advanced statistics" to "고급 통계", "Analysis expression" to "분석 식", "Use current data" to "현재 데이터", "Example" to "예제",
    "ROC curve" to "ROC 곡선", "False positive rate (FPR)" to "위양성률 (FPR)", "Sensitivity (TPR)" to "민감도 (TPR)",
    "ROC/AUC uses fitted data; positive class = 1." to "ROC/AUC는 적합 데이터 기준이며 양성은 1입니다.",
    "Selected column is response; others are predictors." to "선택한 열은 종속변수, 나머지 열은 설명변수입니다.",
    "Dependent variable" to "종속변수",
    "Selected column is response; others are predictors. Logistic response: 0 or 1." to "선택한 열은 종속변수, 나머지 열은 설명변수입니다. 종속변수: 0 또는 1.",
    "Rank tests require data lists" to "순위 검정에는 데이터 목록을 입력하세요",
    "Deviance residual vs fitted probability." to "적합 확률 대비 이탈도 잔차.",
    "R² is undefined for a constant response." to "종속변수가 상수이면 R²는 정의되지 않습니다.",
    "Observation" to "관측 번호", "Pearson residual" to "Pearson 잔차", "Deviance residual" to "이탈도 잔차",
    "Wilcoxon uses x−y for complete pairs." to "Wilcoxon은 완전한 대응 행의 x−y를 사용합니다.",
    "polynomial" to "다항",
    "multiple" to "다중",
    "logistic" to "로지스틱",
    "Survival analysis" to "생존분석",
    "95% CI band" to "95% 신뢰구간 밴드",
    "Survival analysis limit: 20 groups" to "생존분석은 최대 20개 그룹까지 지원합니다",
    "Log-rank needs informative events in all risk sets" to "위험집합에 log-rank 검정에 필요한 사건 정보가 부족합니다",
    "Choose Cox predictors or at least two groups" to "Cox 설명변수 또는 두 개 이상의 그룹을 선택하세요",
    "Wilcoxon" to "Wilcoxon",
    "Mann–Whitney" to "Mann–Whitney",
    "Kruskal–Wallis" to "Kruskal–Wallis",
    "Wilcoxon signed-rank" to "Wilcoxon 부호순위",
    "Mann–Whitney U" to "Mann–Whitney U",
    "Polynomial degree (1–10)" to "다항 차수 (1–10)",
    "Last column is response; previous columns are predictors. Logistic response: 0 or 1." to "마지막 열은 종속변수, 앞 열은 설명변수입니다. 로지스틱 종속변수: 0 또는 1.",
    "Adjusted R²" to "수정 R²",
    "Residual SE" to "잔차 표준오차",
    "Residual Shapiro p" to "잔차 Shapiro p",
    "Deviance" to "이탈도",
    "Coefficient inference" to "계수 추론",
    "Parameter" to "계수",
    "Estimate" to "추정값",
    "95% CI" to "95% 신뢰구간",
    "Residual diagnostics" to "잔차 진단",
    "Residual vs fitted" to "적합값 대비 잔차",
    "Fitted value" to "적합값",
    "Observed" to "관측값",
    "Residual" to "잔차",
    "Standardized" to "표준화 잔차",
    "Leverage" to "레버리지",
    "Cook's D" to "Cook 거리",
    "Row" to "행",
    "Export residual CSV" to "잔차 CSV 내보내기",
    "Copy residual CSV" to "잔차 CSV 복사",
    "Binomial MLE; Wald intervals." to "이항 최대우도 추정 · Wald 근사 신뢰구간.",
    "Inference in log(y); R² and RMSE in original y units." to "계수 추론은 log(y) 척도, R²·RMSE는 원래 y 척도입니다.",
    "Local Jacobian approximation; independent errors with constant variance." to "국소 Jacobian 근사 · 독립 오차와 일정한 분산을 가정합니다.",
    "OLS inference; independent errors with constant variance." to "최소제곱 추론 · 독립 오차와 일정한 분산을 가정합니다.",
    "Residual vs fitted; Durbin–Watson uses input row order." to "적합값 대비 잔차 · Durbin–Watson은 입력 행 순서를 사용합니다.",
    "Showing first 100 rows; export includes all rows." to "처음 100행 표시 · 내보내기는 전체 행을 포함합니다.",
    "Showing first 100 rows; copy includes all rows." to "처음 100행 표시 · 복사는 전체 행을 포함합니다.",
    "Add more observations than coefficients for inference." to "계수 추론에는 계수 수보다 많은 관측값이 필요합니다.",
    "Bounded fit: ordinary coefficient inference is unavailable." to "경계 제약 적합: 일반적인 계수 추론을 제공하지 않습니다.",
    "Regression parameters are not identifiable; inference unavailable." to "계수를 식별할 수 없어 추론을 제공하지 않습니다.",
    "Zero residual variance: coefficient tests are unavailable." to "잔차 분산이 0이므로 계수 검정을 제공하지 않습니다.",
    "Polynomial degree must be an integer from 1 to 10" to "다항 차수는 1~10의 정수여야 합니다",
    "Use at least degree + 1 distinct x values" to "차수 + 1개 이상의 서로 다른 x값을 입력하세요",
    "Regression parameters are not identifiable" to "회귀 계수를 식별할 수 없습니다",
    "Logistic response must contain both 0 and 1" to "로지스틱 종속변수에는 0과 1이 모두 필요합니다",
    "Logistic fit is separated or did not converge; finite inference unavailable" to "로지스틱 데이터가 분리되거나 적합이 수렴하지 않아 유한한 추론값을 구할 수 없습니다",
    "Use one to eight predictors and the response in the last column" to "설명변수 1~8개와 마지막 열의 종속변수를 입력하세요",
    "Statistical values must be finite real numbers" to "통계값은 유한한 실수여야 합니다",
    "Wilcoxon requires equal paired lengths" to "Wilcoxon 대응 표본의 길이가 같아야 합니다",
    "Wilcoxon needs at least one nonzero difference" to "Wilcoxon에는 0이 아닌 차이가 하나 이상 필요합니다",
    "Kruskal–Wallis needs variation between values" to "Kruskal–Wallis에는 값의 변동이 필요합니다",
    "Add" to "추가", "Remove" to "제거", "Clear analysis" to "분석 지우기",
    "Cycle display decimal places" to "표시 소수 자릿수 순환",
    "Yates continuity correction" to "Yates 연속성 보정",
    "Applies only to 2×2 tables. Turn off for Pearson χ²." to "2×2 표에만 적용됩니다. 끄면 보정 없는 Pearson χ²를 계산합니다.",
    "Calculation" to "계산 종류", "Distribution" to "확률 분포",
    "Calculate probability" to "확률 계산", "Reset inputs" to "초기화", "Independent events" to "독립 사건",
    "Calculate parameter" to "모수 계산",
    "Probability examples" to "확률 예제", "Probability operation" to "확률 계산 방식",
    "Favorable outcomes" to "원하는 경우 수", "Total outcomes" to "전체 경우 수",
    "Probability distribution preview" to "확률 분포 미리보기",
    "Range · 0.1%–99.9% quantiles" to "범위 · 0.1%~99.9% 분위수",
    "Preview samples integer masses; some counts are omitted." to "정수별 확률질량을 표본으로 표시하며 일부 횟수는 생략됩니다.",
    "Normal solver requires 0 < q < 1" to "정규 분포 모수 역산에서는 0 < q < 1이어야 합니다",
    "No positive σ satisfies these inputs" to "입력 조건을 만족하는 양수 σ가 없습니다",
    "σ is not uniquely determined when q = 0.5 and x = μ" to "q = 0.5이고 x = μ이면 σ는 하나로 정해지지 않습니다",
    "μ = x − σz, where z is the standard normal quantile." to "μ = x − σz이며 z는 표준정규 분포의 분위수입니다.",
    "σ = (x − μ) / z, where z is the standard normal quantile." to "σ = (x − μ) / z이며 z는 표준정규 분포의 분위수입니다.",
    "undefined" to "정의되지 않음",
    "Mass / density preview" to "확률질량 · 밀도 미리보기",
    "Preview · shaded region is the selected event" to "미리보기 · 색칠한 부분이 선택한 사건",
    "Independent events: P(A ∩ B) = P(A) × P(B)." to "독립 사건: P(A ∩ B) = P(A) × P(B).",
    "Trials are independent with the same success probability." to "성공 확률이 같은 독립 시행입니다.",
    "Geometric X counts trials through the first success (starting at 1)." to "첫 성공까지의 시행 수입니다 (1부터 셉니다).",
    "Negative binomial X counts failures before the r-th success (starting at 0). Total trials = X + r." to "X는 r번째 성공 전까지의 실패 횟수입니다 (0부터 셉니다). 총 시행 수 = X + r.",
    "Negative binomial X counts failures before the r-th success (starting at 0). Total trials = X + r. Smallest supported integer with P(X ≤ x) ≥ q." to "X는 r번째 성공 전까지의 실패 횟수입니다 (0부터 셉니다). 총 시행 수 = X + r. P(X ≤ x) ≥ q를 만족하는 가장 작은 정수입니다.",
    "X counts selected specified items; drawing is without replacement." to "X는 지정 항목 중 뽑힌 개수이며, 중복 없이 뽑습니다.",
    "Smallest supported integer with P(X ≤ x) ≥ q." to "P(X ≤ x) ≥ q를 만족하는 가장 작은 정수입니다.",
    "Inverse cumulative probability." to "누적 확률에 해당하는 값입니다.",
    "Density is not a probability and may exceed 1. For continuous X, P(X = x) = 0." to "밀도는 확률이 아니므로 1보다 클 수 있습니다. 연속 분포에서 P(X = x) = 0입니다.",
    "Enter a number, fraction, or percentage" to "숫자 · 분수 · 백분율을 입력하세요",
    "Enter an integer within the allowed range" to "허용 범위의 정수를 입력하세요",
    "Probabilities must be between 0 and 1" to "확률은 0부터 1 사이여야 합니다",
    "This parameter must be greater than zero" to "0보다 큰 값을 입력하세요",
    "Division by zero in input" to "입력값을 0으로 나눌 수 없습니다",
    "Enter a finite number" to "유한한 숫자를 입력하세요", "Numeric input is too long" to "입력값이 너무 깁니다",
    "Favorable outcomes must not exceed a positive total" to "전체 경우 수는 양수이고, 원하는 경우 수 이상이어야 합니다",
    "Dice count and sides must be positive" to "주사위 개수와 면 수는 양수여야 합니다",
    "Draws and specified items must not exceed total" to "뽑을 수와 지정한 수는 전체 수 이하여야 합니다",
    "Selection count must not exceed item count" to "선택 수는 항목 수 이하여야 합니다",
    "Success count must not exceed trial count" to "성공 횟수는 시행 횟수 이하여야 합니다",
    "Cannot select from zero items" to "항목이 없으면 선택할 수 없습니다",
    "Intersection is inconsistent with P(A) and P(B)" to "교집합 확률이 P(A), P(B)와 맞지 않습니다",
    "Conditioning event has zero probability" to "조건 사건의 확률이 0입니다",
    "Given probability" to "주어진 확률",
    "Add given probability" to "주어진 확률 추가",
    "Remove given probability" to "주어진 확률 제거",
    "Choose at least one given probability" to "주어진 확률을 하나 이상 선택하세요",
    "Given probabilities are inconsistent" to "주어진 확률들이 서로 맞지 않습니다",
    "Given probabilities do not determine a unique answer" to "주어진 확률만으로는 답을 하나로 정할 수 없습니다. 필요한 확률을 추가하세요",
    "Success probability must be greater than zero" to "성공 확률은 0보다 커야 합니다",
    "Required successes must be greater than zero" to "목표 성공 횟수는 0보다 커야 합니다",
    "Average count must be between 0 and 100000" to "평균 발생 횟수는 0부터 100000 사이여야 합니다",
    "Draws and success items must not exceed population" to "추출 수와 성공 항목 수는 모집단 크기 이하여야 합니다",
    "Maximum must be greater than minimum" to "최댓값은 최솟값보다 커야 합니다",
    "Lower bound must not exceed upper bound" to "구간 하한은 상한 이하여야 합니다",
    "Quantile exceeds numerical range" to "분위수가 계산 가능한 범위를 넘었습니다",
    "Calculation failed" to "계산하지 못했습니다", "Numeric exponent is too large" to "입력 지수가 너무 큽니다",
    "Graph colors" to "그래프 색", "Graph color" to "그래프 색",
    "Hue (H)" to "색조 (H)", "Saturation (S)" to "채도 (S)", "Lightness (L)" to "명도 (L)",
    "Reset color" to "색 초기화", "Reset all colors" to "전체 색 초기화",
    "Graph limit reached. Remove a function before adding another." to "그래프 개수 한도에 도달했습니다. 기존 함수를 지운 뒤 추가하세요.",
    "Calculation mode" to "계산 모드", "Choose calculation mode, long press for Scientific/CAS mode" to "계산 모드 선택, 길게 누르면 Scientific/CAS 모드",
    "Stored memory" to "저장된 메모리", "Overwrite mode" to "덮어쓰기 모드", "Insert mode" to "삽입 모드",
    "Clear" to "지우기", "Close" to "닫기", "Done" to "완료", "Cancel" to "취소", "Apply" to "적용",
    "Undo" to "실행 취소", "Cut" to "잘라내기", "Copy" to "복사", "Copy =" to "답 복사", "Copy expr" to "수식 복사",
    "Paste" to "붙여넣기", "Keyboard" to "키보드", "Math input" to "수식 입력",
    "Show exact" to "정확값 보기", "Show decimal" to "소수 보기",
    "Expression input" to "수식 입력", "Undo last input" to "마지막 입력 취소",
    "Instrument setup" to "계산기 설정", "Language" to "언어", "Appearance" to "화면 모양",
    "System" to "시스템", "Light" to "밝게", "Dark" to "어둡게", "Angle unit" to "각도 단위",
    "Internal precision · numeric algorithms" to "내부 정밀도 · 수치 계산", "Display digits · decimal places shown" to "표시 자릿수 · 소수점 아래 자릿수",
    "Custom" to "사용자 지정", "Custom internal precision · 3–200" to "내부 정밀도 직접 입력 · 3–200",
    "Custom display digits · 2–200" to "표시 자릿수 직접 입력 · 2–200",
    "Apply internal precision" to "내부 정밀도 적용", "Apply display digits" to "표시 자릿수 적용",
    "Input font" to "입력 글자", "Output font" to "결과 글자", "Key vibration" to "키 진동",
    "Key sound" to "키 소리", "Save history locally" to "기록을 기기에 저장", "Bracket auto-close" to "괄호 자동 닫기",
    "Calculation history" to "계산 기록", "Search history" to "기록 검색", "All" to "전체", "Recent" to "최근", "Favorites" to "즐겨찾기",
    "Reuse" to "다시 사용", "Delete" to "삭제", "Clear all" to "모두 지우기",
    "Function catalog" to "함수 카탈로그", "Function catalog - help" to "함수 카탈로그 도움말",
    "Help" to "도움말", "Find function" to "함수 찾기", "Search" to "검색",
    "Open the function catalog help" to "함수 카탈로그 도움말 열기", "Loading the catalog reference..." to "카탈로그 설명을 불러오는 중...",
    "Example:" to "예:", "Save a function in Functions to see it here." to "Functions에서 함수를 저장하면 여기에 표시됩니다.",
    "Graph types" to "그래프 종류", "Plot" to "그리기", "Range" to "범위", "Analyze" to "분석", "Table" to "표",
    "Animate" to "애니메이션", "Stop" to "중지", "Parameters ▾" to "매개변수 ▾", "Parameters ▸" to "매개변수 ▸",
    "Fit Y" to "Y 범위 맞춤", "Root" to "근", "Y-intercept" to "y절편", "Intersection" to "교점", "Minimum" to "최솟값",
    "Maximum" to "최댓값", "Inflection" to "변곡점", "Derivative" to "도함수", "Tangent" to "접선",
    "Integral" to "적분", "Arc length" to "호의 길이", "Trace x" to "x 추적",
    "Equation" to "방정식", "Solution" to "해", "Solve" to "풀기", "Solving…" to "푸는 중…",
    "Variable" to "변수", "Variables" to "변수", "Initial guess" to "초깃값",
    "Custom functions" to "사용자 함수", "Import" to "가져오기", "Export" to "내보내기", "Save" to "저장",
    "New" to "새 파일", "Open" to "열기", "Save as" to "다른 이름으로 저장", "Run" to "실행",
    "Running…" to "실행 중…", "Output" to "출력", "Input" to "입력",
    "Data & statistics" to "데이터 및 통계",
    "Summary" to "요약", "Regression" to "회귀", "Tests" to "검정", "Intervals" to "신뢰구간",
    "Import CSV" to "CSV 가져오기", "Import CSV/XLSX" to "CSV/XLSX 가져오기", "Export CSV" to "CSV 내보내기",
    "Select sheet" to "시트 선택", "Continue" to "계속",
    "First row is a header" to "첫 행이 헤더", "Header detected automatically" to "헤더를 자동으로 인식했습니다",
    "No header detected" to "헤더가 감지되지 않았습니다", "Import as" to "가져올 데이터 형식",
    "Choose a CSV column for each variable" to "각 변수에 사용할 CSV 열을 선택하세요", "Choose a column for each variable" to "각 변수에 사용할 열을 선택하세요", "Preview" to "미리보기",
    "Result" to "결과", "Calculate" to "계산", "Amount" to "금액",
    "One equation per line" to "한 줄에 방정식 하나",
    "Variables · comma separated" to "변수 · 쉼표로 구분", "Solve for" to "풀이 변수",
    "Differential equation" to "상미분방정식", "Partial differential equation" to "편미분방정식",
    "Dependent function" to "종속 함수", "Independent variable" to "독립 변수",
    "Initial conditions (optional)" to "초기 조건 (선택)", "Hint (optional)" to "풀이 힌트 (선택)",
    "Example: y(0)=1 or [y(0)=1,y(1)=2]" to "예: y(0)=1 또는 [y(0)=1,y(1)=2]",
    "Name" to "이름", "Parameters" to "매개변수", "Formula" to "공식", "Save function" to "함수 저장",
    "Edit" to "편집", "Insert" to "삽입", "Python code" to "Python 코드", "Enter" to "입력",
    "Open .py" to ".py 열기",
    "Indent" to "들여쓰기", "Outdent" to "내어쓰기",
    "Discard" to "버리기", "Unsaved changes" to "저장하지 않은 변경 사항",
    "Reset" to "초기화", "Reset ranges" to "범위 초기화", "Reset sliders" to "슬라이더 초기화", "Rotate" to "회전", "Tilt" to "기울기", "Zoom" to "확대", "Half height" to "높이 ½", "Full height" to "전체 높이",
    "Graph range" to "그래프 범위", "Automatic z range" to "z 범위 자동 설정",
    "One [x(t),y(t)] pair per line" to "한 줄에 [x(t),y(t)] 한 쌍",
    "r(t) · radians · one curve per line" to "r(t) · 라디안 · 한 줄에 곡선 하나",
    "u(n) · use u(n−1) for recurrences" to "u(n) · 점화식에는 u(n−1) 사용",
    "Implicit Graph" to "Implicit Graph(음함수 그래프)",
    "F(x,y)=0 · e.g. x^2+y^2=1" to "F(x,y)=0 · 예: x^2+y^2=1",
    "Invalid implicit y range" to "음함수 그래프의 y 범위를 확인해 주세요.",
    "Cartesian" to "카테시안",
    "Enter a function y=f(x) or an equation F(x,y)=0" to "함수 y=f(x) 또는 방정식 F(x,y)=0을 입력하세요.",
    "Graph an expression, y = f(x), or an equation F(x,y)=0" to "수식, 함수 y=f(x) 또는 방정식 F(x,y)=0을 입력하세요.",
    "Tap a point on the curve to choose a branch" to "곡선의 점을 눌러 분석할 가지를 선택하세요.",
    "Curve is undefined at this x coordinate" to "이 x 좌표에서 곡선이 정의되지 않습니다.",
    "Derivative graph requires branches expressible as y=f(x)" to "도함수 그래프에는 y=f(x)로 나타낼 수 있는 가지가 필요합니다.",
    "This curve cannot be analyzed as y=f(x) branches" to "이 곡선은 y=f(x) 가지로 분석할 수 없습니다.",
    "These curves cannot be analyzed as y=f(x) branches" to "이 곡선들은 y=f(x) 가지로 분석할 수 없습니다.",
    "The curve lies on the x axis; roots are not isolated" to "곡선이 x축 위에 있어 근을 개별 점으로 나타낼 수 없습니다.",
    "Select two different curves" to "서로 다른 두 곡선을 선택하세요.",
    "Enter one to six implicit equations" to "음함수 방정식을 1~6개 입력하세요.",
    "Enter an equation F(x,y)=0" to "F(x,y)=0 형태의 방정식을 입력하세요.",
    "Equation is true everywhere; enter a curve equation" to "모든 점에서 참인 식입니다. 곡선을 정의하는 방정식을 입력하세요.",
    "f(x) · one per line · [shade] y<f(x) or f, g" to "f(x) · 한 줄에 하나 · 음영: [shade] y<f(x) 또는 f, g",
    "One curve per line · [shade] / [s] -1<x<1 ,-1<y<x · between functions: [s] f, g" to "한 줄에 하나 · [shade] / [s] -1<x<1 ,-1<y<x · 두 함수 사이: [s] f, g",
    "Initial values at n=0 · comma separated" to "n=0의 초깃값 · 쉼표로 구분",
    "Initial time t₀" to "초기 시각 t₀", "Initial y values · comma separated" to "y 초깃값 · 쉼표로 구분",
    "Vector workspace" to "벡터 작업 공간", "Matrix workspace" to "행렬 작업 공간",
    "Insert into calculator" to "계산기에 넣기", "Clear grid" to "격자 지우기", "Operations" to "연산",
    "Operations with the second operand" to "두 번째 피연산자를 사용하는 연산",
    "Variable name or literal such as [[4,5,6]]" to "변수 이름 또는 [[4,5,6]] 같은 값",
    "Stored values · tap to use as the second operand" to "저장된 값 · 누르면 두 번째 피연산자로 사용",
    "Enter values once, then summarize, test, or plot the current dataset." to "데이터를 입력한 뒤 요약, 검정 또는 그래프로 분석합니다.",
    "Dataset name" to "데이터 이름", "Add row" to "행 추가", "One value per line" to "한 줄에 값 하나", "x,y,z data" to "x,y,z 데이터",
    "Direct input" to "직접 입력", "Table editor" to "표 편집", "Expand" to "확장", "Collapse" to "축소",
    "Move column left" to "열 왼쪽으로 이동", "Move column right" to "열 오른쪽으로 이동", "Delete column" to "열 삭제",
    "ANCOVA" to "ANCOVA (공분산분석)", "Generalized linear model (GLM)" to "GLM (일반화 선형모형)",
    "ANCOVA table" to "공분산분석 표", "Adjusted means" to "조정 평균", "Covariate coefficients" to "공변량 계수",
    "Covariate reference values" to "공변량 기준값", "Slope homogeneity" to "회귀 기울기 동질성",
    "SS" to "제곱합", "MS" to "평균제곱", "partial eta2" to "부분 η²", "Residual" to "잔차",
    "raw mean" to "원래 평균", "adjusted mean" to "조정 평균", "Lower CI" to "신뢰구간 하한", "Upper CI" to "신뢰구간 상한",
    "groups" to "그룹 수", "covariates" to "공변량 수", "df residual" to "잔차 자유도", "confidence level" to "신뢰수준",
    "family" to "분포", "link" to "연결함수", "dispersion" to "분산 척도", "Pearson chi2" to "Pearson χ²",
    "null deviance" to "귀무모형 편차", "fitted preview rows" to "적합값 미리보기 행 수", "Fitted observations" to "관측값·적합값",
    "row" to "행", "fitted" to "적합값", "residual" to "잔차", "Pearson residual" to "Pearson 잔차", "Deviance residual" to "편차 잔차",
    "dispersion alpha (NB2, fixed)" to "NB2 분산 alpha (고정)",
    "Quick summaries" to "빠른 요약", "Visualize" to "시각화", "first" to "처음", "last" to "마지막", "Intercept" to "절편", "Plot grouping" to "그래프 그룹", "Visualize & regression" to "시각화 & 회귀", "n columns" to "Column n개", "Column count (1–100)" to "열 개수 (1–100)", "Blank cells are omitted. Group comparisons use all columns." to "빈 셀은 제외하며, 그룹 비교에는 모든 열을 사용합니다.", "Summarize y" to "y 요약",
    "Correlation coefficient (r)" to "상관계수 (r)",
    "Clear regression" to "회귀선 지우기", "Graph fitted expression" to "적합식 그래프로 보기",
    "Independent variable" to "독립변수", "Initial values and bounds (optional)" to "시작값과 범위 (선택)",
    "Custom fitting did not converge to identifiable parameters. Try initial values or bounds, or simplify the model." to "매개변수를 결정할 수 있는 해로 피팅이 수렴하지 않았습니다. 시작값이나 범위를 지정하거나 모델을 단순하게 바꿔 주세요.",
    "Fit custom model" to "사용자 수식 피팅", "ADC example" to "ADC 예제", "IVIM example" to "IVIM 예제", "Exponential decay example" to "지수 감쇠 예제", "Model y =" to "모델 y =", "Fitted parameters" to "피팅 매개변수",
    "Query" to "질의", "Degrees of freedom" to "자유도",
    "Trials n" to "시행 횟수 n", "Success probability p" to "성공 확률 p",
    "Mean λ" to "평균 λ", "Mean μ" to "평균 μ", "Standard deviation σ" to "표준편차 σ",
    "a (lower bound)" to "a (하한)", "b (upper bound)" to "b (상한)",
    "Probability p (0–1)" to "확률 p (0–1)", "Compute" to "계산",
    "Analyze current data" to "현재 데이터 분석", "Hypothesized difference Δ₀" to "가정한 차이 Δ₀",
    "Hypothesized mean μ₀" to "가정한 평균 μ₀", "Confidence level (0–1 or %)" to "신뢰수준 (0–1 또는 %)",
    "Known σx" to "알려진 σx", "Known σ" to "알려진 σ", "Known σy" to "알려진 σy",
    "Alternative hypothesis" to "대립가설", "Alternative odds ratio (ordered categories)" to "대립 Odds ratio (순서 있는 범주)",
    "Insert expression" to "수식 넣기", "Signed interpretation" to "부호 있는 값으로 해석",
    "Scientific constants" to "과학 상수",
    "Recall variable" to "변수 불러오기", "No stored variables" to "저장된 변수가 없습니다",
    "Delete all" to "모두 삭제", "Delete all variables" to "변수 모두 삭제", "Variables & functions" to "변수와 함수",
    "Stats data" to "통계 데이터", "Saved stats data · tap to recall" to "저장된 통계 데이터 · 누르면 불러오기",
    "Columns" to "열별 그룹", "x=group, y=value" to "x=그룹, y=값", "First group" to "첫 번째 그룹", "Second group" to "두 번째 그룹", "Group" to "그룹",
    "First column" to "첫 번째 컬럼", "Second column" to "두 번째 컬럼",
    "Choose two different columns" to "서로 다른 두 컬럼을 선택하세요",
    "Compared columns" to "비교 열", "Row variable" to "행 변수", "Column variable" to "열 변수",
    "Only complete rows in the two selected columns are analyzed." to "선택한 두 컬럼에 모두 값이 있는 행만 분석합니다.",
    "Enter at least two complete rows in the selected columns." to "선택한 두 컬럼에 모두 값이 있는 행을 두 개 이상 입력하세요.",
    "Each selected column needs at least two categories." to "선택한 각 컬럼에 범주가 두 개 이상 필요합니다.",
    "Fisher exact needs exactly two categories in each selected column." to "Fisher 정확 검정은 선택한 각 컬럼에 정확히 두 범주가 필요합니다.",
    "Stored values · tap to select" to "저장된 값 · 눌러서 선택", "Value / expression" to "값 / 수식",
    "User function" to "사용자 함수", "Parameters (comma separated)" to "매개변수 (쉼표로 구분)",
    "Store" to "저장", "Recall" to "불러오기", "Matrix size" to "행렬 크기",
    "Tip calculator" to "팁 계산", "Currency converter" to "통화 변환", "Online / cache" to "온라인 / 저장된 환율",
    "Manual" to "직접 입력", "Bill before tax" to "세전 금액", "Tip amount" to "팁 금액", "Number of people" to "인원수",
    "From (ISO code)" to "변환 전 (ISO 코드)", "To (ISO code)" to "변환 후 (ISO 코드)",
    "⇄ Swap currencies" to "⇄ 통화 맞바꾸기", "Drop decimals" to "소수점 버리기",
    "Update rates" to "환율 갱신", "Customize display buttons" to "표시 버튼 설정",
    "+ Add button" to "+ 버튼 추가", "Find button or function" to "버튼 또는 함수 찾기",
    "No matching buttons" to "일치하는 버튼이 없습니다", "Restore defaults" to "기본값 복원",
    "Complete separation detected; Firth bias reduction applied." to "완전 분리 감지 · Firth 편향 감소 적용",
    "Firth logistic regression; approximate Wald intervals." to "Firth 로지스틱 회귀 · 근사 Wald 신뢰구간",
    "Firth logistic regression; profile penalized-likelihood intervals." to "Firth 로지스틱 회귀 · 프로파일 우도 신뢰구간",
    "Complete separation detected; Firth bias reduction applied with profile penalized-likelihood intervals." to "완전 분리 감지 · Firth 편향 감소 · 프로파일 우도 신뢰구간",
    "Firth bias reduction requested; profile penalized-likelihood intervals." to "Firth 편향 감소 · 프로파일 우도 신뢰구간",
    "Logistic leverage and Cook's D use a one-step GLM approximation." to "로지스틱 leverage·Cook 거리는 GLM 1단계 근사입니다.",
    "Firth influence diagnostics use a GLM approximation at the bias-reduced fit." to "Firth 영향력 진단은 편향 감소 적합점의 GLM 근사입니다.",
    "Penalized influence diagnostics are local approximations with selected predictors held fixed." to "규제 모델의 영향력 진단은 선택된 변수를 고정한 국소 근사입니다.",
    "Influence diagnostics unavailable for singular active predictors." to "선택된 변수의 행렬이 특이하여 영향력 진단을 계산할 수 없습니다.",
    "Forest task" to "포레스트 유형",
    "Auto (0/1 → classification)" to "자동 (0/1 → 분류)",
    "Binary classification" to "이진 분류",
    "Sensitivity" to "민감도",
    "Specificity" to "특이도",
    "OOB sensitivity" to "OOB 민감도",
    "OOB specificity" to "OOB 특이도",
    "OOB accuracy" to "OOB 정확도",
    "OOB C-statistic (AUC)" to "OOB C-statistic (AUC)",
    "Confusion matrix" to "혼동 행렬",
    "Training classification" to "학습 데이터 분류",
    "OOB classification" to "OOB 분류 검증",
    "Predicted 0" to "예측 0",
    "Predicted 1" to "예측 1",
    "Observed 0" to "실제 0",
    "Observed 1" to "실제 1",
    "Decision threshold" to "판정 기준",
    "Positive class" to "양성 클래스",
    "OOB ROC curve" to "OOB ROC 곡선",
    "ROC/AUC uses OOB predictions; positive class = 1." to "ROC/AUC는 OOB 예측 기준 · 양성 클래스 = 1",
    "Permutation importance (OOB ΔAUC)" to "순열 중요도 (OOB ΔAUC)",
    "OOB ROC/AUC requires both classes among observations with OOB predictions; increase tree count." to "OOB ROC/AUC는 OOB 예측이 있는 관측값에 0과 1이 모두 필요합니다. 트리 수를 늘리세요.",
    "ridge" to "Ridge",
    "elasticnet" to "Elastic Net",
    "none" to "없음",
    "None" to "없음",
    "Regularization" to "규제",
    "Regularization α" to "규제 α",
    "L1 ratio (0–1)" to "L1 비율 (0–1)",
    "Log loss" to "로그 손실",
    "Accuracy" to "정확도",
    "Permutation importance (OOB ΔR²)" to "순열 중요도 (OOB ΔR²)",
    "Repeats" to "반복 수",
    "Residual vs fitted" to "잔차와 예측값",
    "lasso" to "Lasso",
    "randomforest" to "랜덤 포레스트",
    "Random Forest" to "랜덤 포레스트",
    "Lasso α" to "Lasso α",
    "Trees (1–200)" to "트리 수 (1–200)",
    "Max depth (1–20)" to "최대 깊이 (1–20)",
    "Random seed" to "난수 시드",
    "Trees" to "트리 수",
    "Max depth" to "최대 깊이",
    "Selected predictors" to "선택된 변수",
    "Feature importance" to "변수 중요도",
    "Predictors standardized; coefficients in original units." to "설명변수 표준화 · 계수는 원래 단위",
    "Training fit; ordinary coefficient inference is unavailable." to "학습 데이터 적합도 · 일반적인 계수 추론은 제공하지 않습니다.",
    "OOB metrics exclude observations with no out-of-bag prediction; increase tree count." to "OOB 예측이 없는 관측값은 검증에서 제외됩니다. 트리 수를 늘리세요."
)

@Composable
fun tr(english: String): String {
    return translateLabel(english,LocalLanguage.current)
}

internal fun translateLabel(english:String,language:String):String {
    val label=when(english){"bayeslinear"->"Bayesian linear regression";"bayeslogistic"->"Bayesian logistic regression";else->english}
    return if (language == "ko") korean[label] ?: label else label
}

@Composable
fun isKorean(): Boolean = LocalLanguage.current == "ko"
