"""Shared social-science analysis definitions used by the schema generator."""
import json
import random

rng=random.Random(341)
survey=[]; social=[]
for i in range(48):
    first=rng.gauss(0,1); second=.5*first+rng.gauss(0,1)
    survey.append([round(3+b*first+rng.gauss(0,.55),3) for b in (1,.8,1.2)]+[round(3+b*second+rng.gauss(0,.55),3) for b in (1,.9,1.1)])
    x=rng.gauss(0,1); m=.7*x+rng.gauss(0,.6); y=.3*x+.8*m+.25*x*m+rng.gauss(0,.7)
    social.append([round(v,3) for v in (x,m,y)])
def data(rows): return json.dumps(rows,separators=(',',':'))
REG='[[0,2],[1,4],[2,3],[3,8],[4,7],[5,9],[6,10],[7,12],[8,11],[9,15],[10,17],[11,16]]'
COUNTS=data([[x,y] for x,counts in enumerate(((0,0,0,1,2,3),(0,0,1,2,3,5),(0,0,1,3,5,8),(0,0,2,4,7,10))) for y in counts])
SPECS=[
 ('cronbach','Cronbach α reliability','Cronbach α 신뢰도','table',',raw',data(survey[:24]),'Rows are subjects, columns are items; raw or standardized alpha. Reverse-code items first. Returns corrected item-total correlations and alpha if deleted. Alpha measures internal consistency.','행은 대상, 열은 문항; raw·standardized α. 역문항은 먼저 역코딩합니다. 수정 문항-총점 상관·문항 삭제 시 α를 제공합니다. α는 내적 일관성을 나타냅니다.'),
 ('efa','Exploratory factor analysis (EFA)','탐색적 요인분석 (EFA)','table',',2,varimax',data(survey),'Select numeric item columns. Extraction: pa (principal axis, default) or pca (principal components). Enter a factor count or parallel for automatic selection. Rotations: varimax, none, promax (power 4) or oblimin (delta 0). Arguments: data,count,rotation,extraction,parallel simulations,seed,percentile. Parallel simulations: 0 = off; automatic selection defaults to 100, percentile 0.95. Reports KMO, Bartlett, communalities, pattern and structure loadings, factor correlations and regression scores. Principal axis uses SMC-reduced eigenvalues for parallel analysis; PCA uses correlation eigenvalues. For correlated factors, interpret communalities with the factor correlations.','숫자 문항 열을 선택합니다. 추출: 주축요인법(pa, 기본) 또는 주성분(pca). 요인 수 또는 자동 선택 parallel을 입력합니다. 회전: varimax·none·promax(지수 4)·oblimin(delta 0). 인수: 자료,요인 수,회전,추출,병렬분석 횟수,시드,백분위. 횟수 0은 끔, 자동 선택 기본값은 100회·백분위 0.95입니다. KMO·Bartlett·공통성·패턴/구조 적재량·요인 상관·회귀 점수를 제공합니다. 병렬분석은 주축요인법에서 SMC 축소 고유값, 주성분에서 상관 고유값을 사용합니다. 사각회전의 공통성은 요인 상관을 함께 반영해 해석합니다.'),
 ('cfa','Confirmatory factor analysis (CFA)','확인적 요인분석 (CFA)','table',',[1,1,1,2,2,2]',data(survey),'Continuous-indicator ML. Enter primary factor IDs in selected indicator order; at least three primary indicators per factor. The first primary loading is fixed at 1. Add cross-loadings as [indicator,factor] pairs on other indicators. Missing data: complete rows or FIML with NA/blank cells under MCAR/MAR; all-empty rows are excluded. Groups: configural (group-specific parameters) or metric (equal raw loadings; other parameters group-specific). Arguments: data,factors,cross-loadings,complete/fiml,group IDs,configural/metric. Reports χ², df, p, CFI, TLI and RMSEA; SRMR for a single complete-data group. Indicator errors are independent.','연속형 지표의 ML 모형입니다. 선택 지표 순서로 주 요인 ID를 입력하며 요인당 주 지표는 최소 3개입니다. 첫 주 적재량은 1로 고정합니다. 다른 지표의 교차적재는 [지표,요인] 쌍으로 지정합니다. 결측 처리: 완전한 행 또는 MCAR/MAR 가정의 FIML(NA/빈 셀); 전부 결측인 행은 제외합니다. 집단: configural(집단별 자유 모수), metric(원척도 적재량 동일·나머지 모수는 집단별 자유). 인수: 자료,요인,교차적재,complete/fiml,집단 ID,configural/metric. χ²·df·p·CFI·TLI·RMSEA, 단일 완전자료 집단의 SRMR을 제공합니다. 지표 오차는 독립을 가정합니다.'),
 ('sem','Structural equation model (SEM)','구조방정식 모형 (SEM)','table',',[1,1,1,2,2,2],[[1,2]]',data(survey),'Use the CFA indicator, cross-loading, missing-data and group settings, then specify acyclic latent paths [source,target]. Arguments: data,primary factors,paths,cross-loadings,complete/fiml,group IDs,configural/metric. Exogenous factors may covary; endogenous disturbances and indicator errors are independent. Metric groups share raw measurement loadings; paths, means, errors and factor variances are estimated separately by group. Path coefficients describe the specified conditional relationships.','CFA와 같은 지표·교차적재·결측·집단 설정에 비순환 잠재 경로 [출발,도착]를 지정합니다. 인수: 자료,주 요인,경로,교차적재,complete/fiml,집단 ID,configural/metric. 외생 요인 간 상관을 허용하며 내생 교란과 지표 오차는 독립을 가정합니다. metric은 원척도 측정 적재량을 동일하게 제약하고 경로·평균·오차·요인분산은 집단별로 추정합니다. 경로 계수는 지정한 조건부 관계를 나타냅니다.'),
 ('manova','MANOVA','MANOVA (다변량 분산분석)','table','',data([[i//8+1,round(r[0],3),round(r[3],3)] for i,r in enumerate(survey[:24])]),'One-way: group column followed by response columns. Factorial: manova(data,factorial,factor count,interaction order), categorical factors first; Type III tests with sum contrasts. Repeated: manova(wide data,repeated,occasions), one subject per row and equal-sized response blocks in occasion order. Tests mean equality across occasions using within-subject contrasts. Reports Pillai, Wilks Rao, Hotelling–Lawley F and Roy upper-bound F. Use complete data and nonsingular residual covariance; independent subjects and normal errors are assumed, with equal group covariance for independent-group designs.','일요인: 그룹 열 뒤에 종속변수 열을 배치합니다. 요인설계: manova(자료,factorial,요인 수,상호작용 차수), 범주 요인 열을 먼저 배치하며 합 대비의 Type III 검정을 사용합니다. 반복측정: manova(넓은 자료,repeated,시점 수), 행당 대상 1명·시점 순서의 동일 크기 반응 블록입니다. 대상 내 대비로 시점 간 평균 동일성을 검정합니다. Pillai·Wilks Rao·Hotelling–Lawley F·Roy 상한 F를 제공합니다. 완전자료·비특이 잔차 공분산이 필요하며 독립 대상·정규 오차, 독립 그룹 설계의 등공분산을 가정합니다.'),
 ('mediation','Mediation analysis','매개 분석','table',',2000,0',data(social[:24]),'Rows: X, M, optional covariates, Y. Single continuous mediator; adjusted OLS direct, total and indirect a×b effects, seeded row-bootstrap percentile CI and Sobel approximation.','열: X·M·선택적 공변량·Y. 단일 연속형 매개변수; 조정 OLS 직접·총·간접 a×b 효과, 시드 기반 행 부트스트랩 백분위 CI·Sobel 근사.'),
 ('moderation','Moderation analysis','조절 분석','table','',data(social[:24]),'Rows: X, W, optional covariates, Y. Centered X/W and X×W interaction; conditional slopes at W mean ± SD with full covariance t inference. Continuous moderator, independent OLS errors.','열: X·W·선택적 공변량·Y. 중심화 X/W·X×W 상호작용; W 평균±SD의 조건부 기울기·전체 공분산 t 추론. 연속형 조절변수·독립 OLS 오차.'),
 ('cramerv','Cramér’s V','Cramér의 V','table','','[[20,5],[7,18]]','Nonnegative integer contingency counts; uncorrected Pearson χ² and Cramér’s V. Independent observations; sparse counts can invalidate χ² p values.','음이 아닌 정수 분할표 빈도; 보정 없는 Pearson χ²·Cramér의 V. 독립 관측; 희소 빈도에서는 χ² p값이 부정확할 수 있습니다.'),
 ('phi','Phi coefficient','phi 계수','table','','[[20,5],[7,18]]','Signed phi for a 2×2 integer count table; swapping one category order reverses its sign. No Yates correction.','2×2 정수 빈도표의 부호 있는 phi; 한 변수의 범주 순서를 바꾸면 부호가 반전됩니다. Yates 보정 없음.'),
 ('cohenkappa','Cohen’s κ agreement','Cohen의 κ 일치도','table',',unweighted','[[25,4,2],[3,20,5],[1,6,24]]','Two-rater square count table with common category order. Unweighted, linear or quadratic kappa; multinomial delta-method SE and asymptotic Wald CI. Weighted categories must be ordered. Observed/expected agreement use the selected weights; exact agreement is also reported.','공통 범주 순서의 두 평가자 정방 빈도표. 무가중·선형·제곱 가중 κ; 다항 델타법 SE·점근 Wald CI. 가중 범주는 순서형이어야 합니다. 관측·기대 일치율은 선택한 가중치를 반영하며 정확 일치율도 제공합니다.'),
 ('dunn','Dunn post-hoc test','Dunn 사후검정','table',',holm','[[1,2,4],[2,3,6],[3,5,8],[4,7,9]]','List of independent sample lists, then holm (default), bonferroni, fdr or none. Pooled midranks, tie correction, two-sided normal p values. Retains the Kruskal–Wallis pooled rank scale.','독립 표본 목록들의 목록과 holm(기본)·bonferroni·fdr·none. 전체 평균순위·동점 보정·양측 정규 p값. Kruskal–Wallis의 전체 순위 척도를 유지합니다.'),
 ('discriminantanalysis','Discriminant analysis (LDA/QDA)','판별분석 (LDA/QDA)','table',',lda,empirical','[[1,2,1],[2,1,1],[1,1,1],[2,3,1],[4,5,2],[5,4,2],[4,4,2],[5,6,2]]','Rows: features, class. LDA pooled / QDA separate unbiased covariances; empirical/equal priors. Optional fourth argument: new feature rows. Training confusion and accuracy use the fitted sample.','열: 변수·분류. LDA 합동 / QDA 개별 불편 공분산; 경험·동일 사전확률. 선택적 넷째 인수: 새 변수 행. 학습 혼동표·정확도는 적합에 사용한 표본 기준입니다.'),
 ('quantreg','Quantile regression','분위회귀','table',',0.5',REG,'Rows: predictors, response; quantile in (0,1). IRLS with subgradient optimality check; asymptotic Gaussian-kernel sandwich / Hall–Sheather bandwidth if residual density supports inference.','열: 설명변수·반응; (0,1)의 분위수. 부분기울기 최적성 검사 IRLS; 잔차 밀도가 추론을 허용하면 Gaussian 커널 샌드위치 / Hall–Sheather 대역폭의 점근 추론.'),
 ('zeroinflated','Zero-inflated regression (ZIP/ZINB)','영과잉 회귀 (ZIP/ZINB)','table',',poisson,intercept',COUNTS,'Rows: predictors, integer counts. Poisson or estimated-alpha NB2 count mixture with logit structural zeros; inflation intercept or same predictors. Joint ML Wald inference.','열: 설명변수·정수 빈도. Poisson 또는 alpha 추정 NB2와 구조적 0의 logit 혼합; 영과잉 절편 또는 같은 설명변수. 공동 ML Wald 추론;'),
 ('tobit','Tobit censored regression','Tobit 검열 회귀','table',',0,none','[[0,0],[1,0],[2,1],[3,3],[4,3],[5,6],[6,5],[7,8],[8,9],[9,8],[10,11],[11,12]]','Rows: predictors, observed response; lower bound (default 0), upper bound (default none). Type-I normal censoring, joint ML coefficient/sigma inference. Values at bounds are censored; coefficients refer to the latent response.','열: 설명변수·관측 반응; 하한(기본 0)·상한(기본 none). Type-I 정규 검열·공동 ML 계수/sigma 추론. 경계값은 검열 관측, 계수는 잠재 반응 기준.'),
 ('hcluster','Hierarchical clustering','계층적 군집분석','table',',2,ward,1','[[1,1],[1,2],[2,1],[8,8],[8,9],[9,8]]','Independent agglomerative analysis; clusters, single/complete/average/Ward Euclidean linkage, standardize 1/0. Returns all merges, heights, sizes and cut assignments. Leaves 1…n, merge nodes n+1…2n−1.','독립 응집 분석; 군집 수·single/complete/average/Ward 유클리드 연결·표준화 1/0. 전체 병합·거리·크기·절단 배정. 잎 1…n, 병합 노드 n+1…2n−1.'),
]

def forms(field,col,multi,group_fields):
    choice=lambda key,en,ko,default,values: field(key,en,ko,'choice',default,[(v,e,k) for v,e,k in values])
    scaling=choice('standardize','Scaling','척도','1',[('1','Standardize','표준화'),('0','Raw scale','원척도')])
    features=[multi('columns','Feature / item columns','변수·문항 열')]
    regression=[col('response','Response','반응 열',-1),multi('predictors','Predictors','설명변수 열')]
    measurement=features+[field('factors','Primary factor IDs in selected order','선택 순서의 주 요인 ID','text','1,1,1,2,2,2'),
        field('cross','Cross-loadings: indicator,factor;…','교차적재: 선택 지표 번호,요인;…','text',''),
        choice('missing','Missing data','결측 자료','complete',[('complete','Complete rows required','완전한 행 필요'),('fiml','FIML (MAR, continuous)','FIML (MAR, 연속형)')]),
        choice('groupMode','Groups','집단','single',[('single','Single group','단일 집단'),('multi','Multiple groups','다집단')]),
        dict(col('group','Group column','집단 열',0),when={'groupMode':['multi']}),
        dict(choice('invariance','Invariance','불변성','configural',[('configural','Configural (group free)','형태 (집단별 자유)'),('metric','Metric (equal loadings)','측정 (적재량 동일)')]),when={'groupMode':['multi']})]
    layout=choice('layout','Data layout','자료 형태','counts',[('counts','Contingency counts','분할표 빈도'),('pairs','Paired categories','범주 쌍')])
    categorical=[layout,dict(multi('columns','Count columns','빈도 열'),when={'layout':['counts']}),dict(col('first','First variable / rater','첫 변수·평가자',0),when={'layout':['pairs']}),dict(col('second','Second variable / rater','둘째 변수·평가자',1),when={'layout':['pairs']})]
    social=[col('x','Predictor X','설명변수 X',0),col('middle','Mediator M / moderator W','매개 M·조절 W',1),col('response','Outcome Y','결과 Y',-1),field('covariates','Covariate columns (optional)','공변량 열 (선택)','columns','')]
    return {
      'cronbach':features+[choice('mode','Alpha','α','raw',[('raw','Raw','원척도'),('standardized','Standardized','표준화')])],
      'efa':features+[field('factors','Factor count or parallel','요인 수 또는 parallel','text','2'),
        choice('extraction','Extraction','추출','pa',[('pa','Principal axis (common factors)','주축요인법 (공통요인)'),('pca','Principal components','주성분')]),
        choice('rotation','Rotation','회전','varimax',[('varimax','Varimax (orthogonal)','Varimax (직교)'),('promax','Promax (oblique, power 4)','Promax (사각, 지수 4)'),('oblimin','Oblimin (oblique, delta 0)','Oblimin (사각, delta 0)'),('none','None','없음')]),
        field('parallelSamples','Parallel simulations (0 = off; parallel count uses 100)','병렬분석 횟수 (0=끔; parallel 자동 선택은 100회)','number','0'),field('seed','Seed','시드','number','0'),field('percentile','Parallel percentile (0–1)','병렬분석 백분위 (0~1)','number','0.95')],
      'cfa':measurement,'sem':measurement+[field('paths','Latent paths: source,target;…','잠재 경로: 출발,도착;…','text','1,2')],
      'manova':[choice('design','Design','설계','oneway',[('oneway','One factor','일요인'),('factorial','Factorial (Type III)','요인설계 (Type III)'),('repeated','Repeated (wide rows)','반복측정 (대상별 넓은 행)')]),
        dict(col('group','Group','그룹 열',0),when={'design':['oneway']}),dict(multi('factorColumns','Factor columns','요인 열'),default='0,1',when={'design':['factorial']}),
        multi('responses','Response columns (occasion blocks for repeated)','종속변수 열 (반복측정은 시점별 블록 순서)'),
        dict(field('order','Interaction order','상호작용 차수','number','2'),when={'design':['factorial']}),
        dict(field('occasions','Repeated occasions','반복 시점 수','number','3'),when={'design':['repeated']})],
      'mediation':social+[field('samples','Bootstrap samples','부트스트랩 횟수','number','2000'),field('seed','Seed','시드','number','0')],
      'moderation':social,'cramerv':categorical,'phi':categorical,
      'cohenkappa':categorical+[choice('weights','Weights','가중치','unweighted',[('unweighted','Unweighted','무가중'),('linear','Linear','선형'),('quadratic','Quadratic','제곱')]),dict(field('categories','Category order (comma separated; optional for unweighted)','범주 순서 (쉼표 구분; 무가중은 선택)','text',''),when={'layout':['pairs']})],
      'dunn':group_fields+[choice('adjustment','P-value adjustment','p값 보정','holm',[(v,e,e) for v,e in [('holm','Holm'),('bonferroni','Bonferroni'),('fdr','FDR (BH)'),('none','None')]])],
      'discriminantanalysis':[col('response','Class','분류 열',-1),multi('predictors','Features','변수 열'),choice('method','Method','방법','lda',[('lda','LDA','LDA'),('qda','QDA','QDA')]),choice('prior','Class priors','분류 사전확률','empirical',[('empirical','Empirical','경험 빈도'),('equal','Equal','동일')])],
      'quantreg':regression+[field('quantile','Quantile','분위수','number','0.5')],
      'zeroinflated':regression+[choice('family','Count family','빈도 분포','poisson',[('poisson','Poisson (ZIP)','Poisson (ZIP)'),('nbinom','Negative binomial (ZINB2)','음이항 (ZINB2)')]),choice('inflation','Inflation predictors','영과잉 설명변수','intercept',[('intercept','Intercept only','절편만'),('same','Same predictors','같은 설명변수')])],
      'tobit':regression+[field('lower','Lower bound (none = absent)','하한 (none = 없음)','text','0'),field('upper','Upper bound (none = absent)','상한 (none = 없음)','text','none')],
      'hcluster':features+[field('clusters','Clusters','군집 수','number','2'),choice('linkage','Linkage','연결 방법','ward',[(v,v.title(),v.title()) for v in ('ward','single','complete','average')]),scaling],
    }
