export const pythonImports=['import math','import statistics','import random','import itertools','from fractions import Fraction','import sympy as sp','import symvacas_catalog as calc'];
export const pythonSnippets=[['Function','def function_name(value):\n    return value\n',4],['Main','if __name__ == "__main__":\n    main()\n'],['Class','class ClassName:\n    def __init__(self):\n        pass\n',6],['For loop','for item in items:\n    print(item)\n',4],['Try / except','try:\n    pass\nexcept Exception as exc:\n    print(exc)\n',9],['input','input()',6],['print','print()',6],['sp.N','sp.N()',5,'import sympy as sp']];
const common='abs all any bool dict enumerate filter float int len list map max min open print range round set sorted str sum tuple zip False None True and as class def elif else except for from if import in is lambda not or pass return try while with yield math statistics random itertools sympy sp calc Fraction'.split(' ');
const members={math:'acos asin atan ceil cos e exp floor log pi sin sqrt tan'.split(' '),statistics:'mean median mode stdev variance'.split(' '),random:'choice randint random shuffle'.split(' '),sp:'diff expand factor integrate Matrix pi simplify sin solve sqrt symbols'.split(' ')};
export function pythonCompletions(source,cursor){const prefix=/[A-Za-z_][A-Za-z0-9_]*$/.exec(source.slice(0,cursor))?.[0]||'',start=cursor-prefix.length,module=/([A-Za-z_][A-Za-z0-9_]*)\.$/.exec(source.slice(0,start))?.[1];if(prefix.length<2)return [];return [...new Set(module?members[module]||[]:[...common,...source.matchAll(/\b[A-Za-z_][A-Za-z0-9_]*\b/g)].map(n=>Array.isArray(n)?n[0]:n))].filter(n=>n.startsWith(prefix)&&n!==prefix).sort().slice(0,8);}
export function insertPythonImport(source,cursor,line){const rows=source.split('\n');if(rows.some(s=>s.trim()===line))return {source,cursor};let position=source.startsWith('#!')?source.indexOf('\n')+1:0;if(position===0&&source.startsWith('#!'))position=source.length;const inserted=(position===source.length&&source.length&&!source.endsWith('\n')?'\n':'')+line+'\n';return {source:source.slice(0,position)+inserted+source.slice(position),cursor:cursor+(cursor>=position?inserted.length:0)};}
export function bindPythonEditor(field,{toolbar,suggestions,onEdit,copy,paste}){
  let undo=[],redo=[],before=field.value;
  function remember(){undo.push(before);if(undo.length>100)undo.shift();redo=[];before=field.value;}
  function apply(source,cursor=source.length){remember();field.value=source;before=source;field.setSelectionRange(cursor,cursor);field.focus({preventScroll:true});onEdit();complete();}
  function replace(text,cursor=text.length){const start=field.selectionStart;apply(field.value.slice(0,start)+text+field.value.slice(field.selectionEnd),start+cursor);}
  function button(text,action){const button=document.createElement('button');button.type='button';button.textContent=text;button.onclick=action;toolbar.append(button);return button;}
  button('Undo',()=>{if(undo.length){redo.push(field.value);field.value=undo.pop();before=field.value;onEdit();complete();}});button('Redo',()=>{if(redo.length){undo.push(field.value);field.value=redo.pop();before=field.value;onEdit();complete();}});
  button('Cut',()=>{if(field.selectionStart!==field.selectionEnd){copy(field.value.slice(field.selectionStart,field.selectionEnd));replace('');}});button('Copy',()=>copy(field.value.slice(field.selectionStart,field.selectionEnd)||field.value));button('Paste',async()=>{try{replace(await paste());}catch{field.focus();}});
  for(const [label,values] of [['import',pythonImports.map(line=>[line,line])],['Function',pythonSnippets]]){const select=document.createElement('select'),empty=document.createElement('option');empty.value='';empty.textContent=label;select.append(empty);for(const [i,[name]] of values.entries()){const option=document.createElement('option');option.value=String(i);option.textContent=name;select.append(option);}select.onchange=()=>{if(select.value==='')return;const choice=values[Number(select.value)];if(label==='import'){const edit=insertPythonImport(field.value,field.selectionStart,choice[1]);apply(edit.source,edit.cursor);}else{replace(choice[1],choice[2]??choice[1].length);if(choice[3]){const edit=insertPythonImport(field.value,field.selectionStart,choice[3]);apply(edit.source,edit.cursor);}}select.value='';};toolbar.append(select);}
  function indent(outdent=false){const source=field.value,start=source.lastIndexOf('\n',field.selectionStart-1)+1,end=source.indexOf('\n',field.selectionEnd),limit=end<0?source.length:end,lines=source.slice(start,limit).split('\n').map(line=>outdent?line.replace(/^ {1,4}|^\t/,''):'    '+line),replacement=lines.join('\n');apply(source.slice(0,start)+replacement+source.slice(limit),start+replacement.length);}
  button('Indent',()=>indent());button('Outdent',()=>indent(true));
  function complete(){suggestions.replaceChildren();for(const word of pythonCompletions(field.value,field.selectionStart)){const button=document.createElement('button');button.textContent=word;button.onclick=()=>{const prefix=/[A-Za-z_][A-Za-z0-9_]*$/.exec(field.value.slice(0,field.selectionStart))?.[0]||'',end=field.selectionEnd;field.setSelectionRange(field.selectionStart-prefix.length,end);replace(word);const module=/([A-Za-z_][A-Za-z0-9_]*)\.$/.exec(field.value.slice(0,field.selectionStart-word.length))?.[1],importLine=module==='sp'?'import sympy as sp':module&&members[module]?'import '+module:word==='sp'?'import sympy as sp':word==='calc'?'import symvacas_catalog as calc':word==='Fraction'?'from fractions import Fraction':members[word]?'import '+word:null;if(importLine){const edit=insertPythonImport(field.value,field.selectionStart,importLine);apply(edit.source,edit.cursor);}};suggestions.append(button);}}
  field.addEventListener('input',()=>{remember();onEdit();complete();});field.addEventListener('keyup',complete);field.addEventListener('click',complete);
  field.addEventListener('keydown',event=>{if(event.key==='Tab'){event.preventDefault();event.stopImmediatePropagation();if(event.shiftKey||field.selectionStart!==field.selectionEnd)indent(event.shiftKey);else replace('    ');}else if(event.key==='Enter'&&!event.ctrlKey&&!event.metaKey){const line=field.value.slice(field.value.lastIndexOf('\n',field.selectionStart-1)+1,field.selectionStart),prefix=/^\s*/.exec(line)[0]+(line.trimEnd().endsWith(':')?'    ':'');event.preventDefault();replace('\n'+prefix);}});
  return {replace};
}
